### ISSUE TITLE
Explore from here, then saving a chart to a dashboard causes changes to be overwritten.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10039]
### Description

If you `explore from here` on a dashboard, then from that new tab, save the chart. 

Then go back to the original dashboard tab and hit `explore from here` again, then save a chart again, your first chart (and any changes you made after it) will be overwritten.

### Steps to Reproduce the Bug or Issue

1. Visit dashboard and use Explore from here on any of the charts to review the results in the separate view.
2. Make an adjustments to the Explore view (adding new data or changing the visual layout) proceed with Save Chart to the Dashboard.
3. Stay on the same page and press Explore from here once again. Make an adjustments to the visual or data and press Save Chart (the Dashboard will be selected by default)
4. After saving it you will be redirected to the dashboard page with only one added visual ( all the previously added to dashboard visuals will be deleted). In case you will save these changes to dashboard the visuals would be deleted without recovery.

### Cloud or self-hosting

None

**Comment by joaoviana** [comment]
Reopening this since it was reverted in: https://github.com/lightdash/lightdash/pull/10067

Which was causing errors: https://lightdash.sentry.io/issues/5348865030/?alert_rule_id=15154466&alert_type=issue&environment=cloud_beta&notification_uuid=3b223a66-60fb-4aef-8546-e354db993b09&project=4507168845529088&referrer=issue_alert-slack
And: https://lightdash.sentry.io/issues/4701130771/?referrer=issue_alert-slack&notification_uuid=943afc29-a7c1-4297-961a-1ad08ce89375&environment=cloud_beta&alert_rule_id=9333608&alert_type=issue

**Comment by joaoviana** [comment]
Worked on this issue first with @magnew : https://github.com/lightdash/lightdash/pull/10071

**Comment by joaoviana** [comment]
PR above ^ (10071) fixes issue
