### ISSUE TITLE
The user should know that their projects must be dbt 1.0.0 compatible before they fill out the 'Connect your Project' form, rather than after.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#1043]
### Describe the bug

Users that haven't upgraded their dbt version yet will fill out the `Connect your project` form and hit `Test connection` only to find out that they need to upgrade in the error log. They should be made aware of this requirement _before_ they fill the form out 
### To Reproduce
Go to `Connect a Project`

### Expected behavior

We should clearly communicate that the user's project must be compatible with `dbt 1.0.0` at the start of the form. We could possibly link to https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-1-0-0 and hopefully, with the recent addition of Chatwoot we should be able to provide support at this point if they need it. 

### Screenshots or Loom video

Suggestion:
![Screenshot 2021-12-20 at 15 52 33](https://user-images.githubusercontent.com/12776522/146797044-078f42bd-6422-45c2-b4dc-ce5c869d557d.png)

**Comment by PriPatel** [comment]
I'm not sure if :
`upgrade dbt_utils to version 0.7.6  
`
should be mentioned at this point as well?

**Comment by ZeRego** [comment]
> I'm not sure if :
upgrade dbt_utils to version 0.7.6
should be mentioned at this point as well?

I don't think we should mention it here. Otherwise is going to become a big text.

@PriPatel what you think about this ? I tried to add a second text with the link to the dbt docs


![Screenshot 2022-01-21 at 11 20 42](https://user-images.githubusercontent.com/9117144/150518807-d355b46f-d97c-40f6-b433-d749b70c3289.png)

**Comment by PriPatel** [comment]
Thanks @ZeRego makes sense.
I think to keep it simple and on one line.. can the `dbt version 1.0.0` link out to the official docs instead? I feel like thats the natural thing to click on if you want to know more!
