### ISSUE TITLE
Lightdash doesn't connect when SSL is required for Redshift

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#1046]
![image](https://user-images.githubusercontent.com/9117144/146924002-38acc973-c326-41f4-9f2a-b6e14f5f1d37.png)

**Comment by ZeRego** [comment]
Relevant docs: 
https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html
https://github.com/brianc/node-postgres/tree/master/packages/pg-connection-string

**Comment by owlas** [comment]
@ZeRego for testing, I'll tear down the existing redshift cluster and start again.

**Comment by owlas** [comment]
Update:

* PR #1057 - adds the AWS certificate bundle that allows Lightdash to connect directly to Redshift with `sslmode=require,verify-ca,verify-full`
* We still cannot connect to redshift clusters behind a custom domain because `node-pg` is rejecting the custom hostname for all sslmodes. This behaviour seems to be different to most postgres clients; users have reported that sslmode=require,verify-ca should check certificates but not fail for domains that don't match. To mimic this exact behaviour I think we need to follow this workaround from this [open issue on node-pg](https://github.com/brianc/node-postgres/issues/2178#issuecomment-619161131)
* When we set `sslmode=verify-ca,verify-full` dbt compile is failing because it looks for a certificate at `~/.postgresql/root.crt`

Fixes we need to make:
* Fix dbt compile: copy the AWS cert bundle to `~/.postgresql/root.crt` OR find a way to customise that path
* Fix node-pg to skip hostname check unless `sslmode=verify-full` [fix](https://github.com/brianc/node-postgres/issues/2178#issuecomment-619161131)

**Comment by owlas** [comment]
Also we should update the docs to explain exactly what happens with the different postgres modes. Or maybe even indicate in the UI the sort of protection users get with the different SSL modes.
