### ISSUE TITLE
New SQL runner catalog 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#10516]
Similar to https://github.com/lightdash/lightdash/issues/1804

### Requirements
- Build a new endpoint to fetch `all tables` from a warehouse 
- Build another endpoint to fetch all fields from a table. 
- we need a way to figure out if this is too big (and cut it off if this is the case)
- we should cache these results
- there should be a way to refresh the cache
- at the moment, we only retrieve the tables, not the fields. We want to also collect the field names (not just the table names)

### out of scope
- Joins.

**Comment by owlas** [comment]
@rephus and @ZeRego also wanted to consider how this might interact with people that have their own override warehouse credentials. We could store these per warehouse connection rather than per project. If there's an obvious way to get that working cleanly then do it. Otherwise just store the warehouse catalog for project
