### ISSUE TITLE
Investigate chart config

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#10567]
Is a requirement we have a new chart config and component with the idea of replacing the existing explore chart config and component in the future.

We are going to start with table and bar chart with limited configuration so we can have something usable for the MVP. We will support all existing(and more) types and configuration after the MVP.

Things to consider:

- A new table component that is generic 🟢
    - freeze header/footer 🟢
    - freeze columns 🟡
    - has pagination 🟡
    - has lazy loading scroll 🟢
    - has pivoting 🟡
    - has totals 🟡
    - has row subtotals 🟡
    - doesn’t know about dimension/metrics/table calcs 🟢
    - doesn’t know about permissions 🟢
    - doesn’t know about cell/column actions 🟢
    - doesn’t know about formatting 🟢
    - this component should be the same as the table viz 🟢
- A new chart component + config 🟢
    - something like this: https://www.figma.com/proto/TWqJmWNsnDqjTXlZEtmlWa/newnew?node-id=2343-3289&t=eEIXE1JSUExATv0U-0&scaling=min-zoom&content-scaling=fixed&page-id=2343%3A2480
    - bar viz type 🟢
        - The only configuration options for the bar chart are:
            - choosing the fields for the x & y axes and teh group
            - When you pick a field for the y-axis, you need to choose an aggregation type
    - needs to use echarts lib 🟢
    - doesn’t know about dimension/metrics/table calcs 🟢
    - doesn’t know about click actions 🟢
    - doesn’t know about permissions 🟢
    - doesn’t know about echarts 🟢
    - doesn’t know about formatting 🟢
    - has pivoting 🟡
    - has totals 🟡

**Comment by joaoviana** [comment]
## Proposal - Chart config + thinking ahead when user adds a SQL chart to a dashboard

How we can render a SQL chart of type Table on a Dashboard tile

1. In `GridTile` we have a separate type for `DashboardTileTypes` - `SQL_CHART`
2. Create `DashboardSqlChartTile` in ./DashboardChartTile.tsx`
3. Use `GenericDashboardChartTile` which will wrap it in `TileBase`
4. Ensure we pass empty props to `MetricQueryDataProvider`
5. In `DashboardChartTileMain`, we pass a different type `chartAndResults` to `ValidDashboardChartTile`
6. `ValidDashboardChartTile` will reference the `VisualizationProvider`. This is where it will initialize the chart type config. I believe this should handle everything for us and we should make changes to the provider to handle the new chart type.
7. Since we're starting with `ChartType.Table`, we ensure that `VisualizationTableConfig` can accept an empty `itemsMap`, an acceptable `resultsData`, and can ignore other configs like: `columnOrder`, `validPivotDimensions`, `filters`, etc.
- then, on `VisualizationConfigTable`, we can pass the `resultsData` to the `Table` component
- then, the `Table` will be rendered in `LightdashVisualization` with the `SimpleTable` component. 
- this `SimpleTable` component should handle empty `columnOrder`, and any other extra configurations, for example: `hideRowNumbers`, `showColumnCalculation`, etc. 
- `SimpleTable` should be receive the correct `data` (rows) and `columns` the columns from the results file

**Comment by joaoviana** [comment]
## Proposal 3

### Table chart config

Table config will only include `columns` and it's similar to `ColumnProperties` but with now `visible`,`label`,`frozen` are required and have defaults - do we want this approach of applying defaults?
```ts
type TableChartSql = {
    columns: Record<string, {
        visible: boolean; // default true
        label: string; // default is the `name` of the field/column
        frozen: boolean; // default false
        type: string; // Do we feel that this would be necessary? 
    }>;
}
```
alternative with an array (better to pass to the Table component, but could be worse for lookup)
```ts
type TableChartSql = {
    columns: {
        name: string;
        label?: string;
        visible: boolean;
        frozen?: boolean;
        type: string; // ?Necessary?
    }[];
};
```


### Bar chart config

```ts

type BarChartSqlConfig = {
    type: 'bar';
    style: {
        orientation: 'vertical'|'horizontal';
        stacked: boolean;
        legend: {
            position: 'top'|'bottom'|'left'|'right';
            align: 'start'|'center'|'end';
        } | undefined;
    }
    axis: {
        x: {
            name: string;
            label: string;
            type: string; // Don't think it's necessary
        }[]
        y: {
            cols: {
                name: string;
                type: string; // Don't think it's necessary
                // aggregation: 'sum'|'count'|'avg'|'mode'|'median'|'min'|'max';
            }[];
            label: string;
        }[]
    }
}
```

We could have instead: 
`xAxis`:...
`yAxis`:...

I've also seen 
`primary` (instead of `xAxis`)
`secondary` (instead of `yAxis`)

The above will keep track of: 
- Fields names/labels
- Bar chart config orientation
- Stacking/Grouping
- Legend (if we care about it at the moment)

**Comment by ZeRego** [comment]
> do we want this approach of applying defaults?

We can save this as a JSONB in the database and call a util function `getValidChartConfig` in the model. This way we don't have to constantly migrate the database and be sure the data has the valid properties & defaults. 

> Table config will only include columns and it's similar to ColumnProperties but with now visible,label,frozen are required and have defaults - do we want this approach of applying defaults?

I prefer the `record` over the `array` as it's easier&performant to convert to array. `Object.values(...)`.

>  type: string; // Do we feel that this would be necessary? 

What is this type referring to? string/number/etc? if so, I think this should be inherited from the results via the column reference. 

Will the record key be a reference to the results column? perhaps we should have a property with the same value.
Should we have a `order: number` property? 

> type: 'bar';

User may want 1 metric with bars and another metric with line.
We can have a `defaultType: 'bar';` at the top and then a `type?` inside the yaxis. The default type is applied unless the user sets it to a specific type. 

> stacked: boolean;

This should be inside the yAxis as I may want 1 metric with stacked bars and another without stack bars or another type.

**Comment by joaoviana** [comment]
> We can save this as a JSONB in the database and call a util function `getValidChartConfig` in the model. This way we don't have to constantly migrate the database and be sure the data has the valid properties & defaults.

👍 Sounds good

> I prefer the `record` over the `array` as it's easier&performant to convert to array. `Object.values(...)`.

Cool, agree!

> What is this type referring to? string/number/etc? if so, I think this should be inherited from the results via the column reference.

Sounds good and keeps it separated 👍 

> Will the record key be a reference to the results column? perhaps we should have a property with the same value. Should we have a `order: number` property?

yes, the key would be a reference to the `results` column`, but adding the property now as well as the `order: number`

> User may want 1 metric with bars and another metric with line. We can have a `defaultType: 'bar';` at the top and then a `type?` inside the yaxis. The default type is applied unless the user sets it to a specific type.

Oooh I see - makes sense, updating as well.

> This should be inside the yAxis as I may want 1 metric with stacked bars and another without stack bars or another type.

Good point, updating that as well!


## Proposal 3 - UPDATED after feedback (see UPDATED keyword)

### Table chart config


```ts
type TableChartSqlConfig = {
    columns: Record<string, {
        visible: boolean; 
        name: string; // UPDATED: the key (column key) of this object
        label: string;
        frozen: boolean;
        order?: number; // UPDATED: optional, specifies the order of the columns
    }>;
}
```

### Bar chart config

```ts

type BarChartSqlConfig = {
    defaultType: 'bar'; // UPDATED: renamed from `type` to `defaultType`
    style: {
        orientation: 'vertical'|'horizontal';
        legend: {
            position: 'top'|'bottom'|'left'|'right';
            align: 'start'|'center'|'end';
        } | undefined;
    }
    axis: {
        x: {
            name: string;
            label: string;
        }[]
        y: {
            cols: {
                name: string;
                stacked?: boolean; // UPDATED: specific to each metric
                chartType?: 'bar' | 'line'...etc; // UPDATED: allows mixed chart types
            }[];
            label: string;
        }[]
    }
}
```

Question on `y-axis` `label` and since we want to support mixed charts - probably better to have the `label` inside `cols`?
