### ISSUE TITLE
Investigate how we are going to save SQL query

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#10594]
Requirements:
- save SQL query charts in database
- save dashboard with a SQL chart tile
- SQL charts should be listed alongside explore charts ( chart page / space chart tab / dashboard new tile dropdown )

What tables/columns do we need?
What endpoints do we need to update/create?
What types do we need to update/create?

**Comment by rephus** [comment]
### save SQL query charts in database

Create a new table `saved_sql` Similar schema to `saved_queries` 
![image](https://github.com/lightdash/lightdash/assets/1983672/ac5f5bda-8714-414d-b353-828dea85539a)

However, for SQL, we don't need `additional_metrics` `custom_dimensions` `fields` or `sorts` as they are specified in the SQL. 
Instead, we add a `sql: text` to the `version` table. 

I created a draft here: 
https://github.com/lightdash/lightdash/pull/10610

- [x] add dashboard_uuid to support `sql charts within dashboards`

### save dashboard with a SQL chart tile

Create a new `dashboard_tile_sql_charts` table, simliar to `dashboard_tile_charts` but instead of `saved_chart_id` , we point to `saved_sql_uuid` 

### SQL charts should be listed alongside explore charts ( chart page / space chart tab / dashboard new tile dropdown )

Update SavedChatModel to read from `saved_sql`
`ChartSummary` should be compatible with the new `saved_sql` chart

**Comment by ZeRego** [comment]
Chart summary -> from: 'explore' | 'sql' | 'dbt_semantic_layer' 

new tile type? 

/saved/uuid - get SQL chart or Explore chart
[if SQL chart] /saved/uuid/results - create job id for results + endpoint to get results stream

( if we change existing explore chart requests, update scheduler delivery code )
