### ISSUE TITLE
Embedding LIGHTDASH_CSP_ALLOWED_DOMAINS not working as expected

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#10785]
### Description

A customer is seeing an issue with LIGHTDASH_CSP_ALLOWED_DOMAINS. We have included their domain in this list and it appears to be set in the `Content-Security-Policy` headers, but they are still seeing a csp security error in the console. Needs investigation. 

Internal thread for context here: https://lightdash.slack.com/archives/C047XUL7QAZ/p1721233249057149

### Steps to Reproduce the Bug or Issue

N/A

### Cloud or self-hosting

None

**Comment by rephus** [comment]
Hi @ZeRego do you have any idea why this is not working as expected ?

**Comment by ZeRego** [comment]
Error message:
`Refused to frame X because an ancestor violates the following Content Security Policy directive:  frame-ancestors: 'self', https://*`

The domain that embeds the Lightdash page doesn't use the https protocol.
This is not related to LIGHTDASH_CSP_ALLOWED_DOMAINS config as this env var is to expand the list of domains from where Lightdash can import/use files and not the domains that can embed Lightdash.

For that specific user, they were testing the embed in their development env `http://localhost:8080/`
