### ISSUE TITLE
`lightdash dbt run` overwrites custom description for state field

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#10831]
### Description

I am creating a new model and ran into this, but my `state` is not the same as the the one in docs.

### Steps to Reproduce the Bug or Issue

1. In our internal analytics project, create a field named `state` and give it a custom description
2. Run `lightdash dbt run` on that model
3. The description will be overwritten with the docstring reference

Video: https://www.loom.com/share/f324aa4654074aca801b40f2225c1ced

### Cloud or self-hosting

None

**Comment by joaoviana** [comment]
Been looking into this and will try to reproduce in our lightdash analytics repo.
You're right tho, why is it replacing the docs? 🤔 

What happens if you just run `lightdash dbt run`? 

From the code logic it should only replace if there's any docs reference, and I don't see that being the case here.

**Comment by jpetey75** [comment]
@joaoviana there is a docs reference for `state` it's in the Stripe package that is used by our internal dbt project https://lightdash.slack.com/archives/C01788UVBUG/p1722028471349699?thread_ts=1721868961.135709&cid=C01788UVBUG
