### ISSUE TITLE
`percent change from previous` quick calculation is not giving the correct results

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10971]
### Description

<img width="1361" alt="image" src="https://github.com/user-attachments/assets/520de0b8-3b7e-4db8-beb4-2894023ae0e9">

```
(
              ${pages.page_view_count} / NULLIF(LAG(${pages.page_view_count}) OVER(ORDER BY `pages_date_year` DESC ) ,0)
            ) - 1
```

This should be `ASC` instead of `DESC`.

### Steps to Reproduce the Bug or Issue

create a table calculation using the `quick calculation` see that it's wrong. 

### Cloud or self-hosting

None

**Comment by rephus** [comment]
IN here we apply the same order as the field, I can see your results are `ORDER BY `pages_date_year` DESC` so we apply the same order to the table calculation, otherwise they will not match. right ?  Is this happening to other quick TCs ? 

To be honest, I'm not sure if changing the order fixes the issue. The TC on the left is with Order Desc, the one in the right is with Order ASC

![image](https://github.com/user-attachments/assets/efdaddae-4afe-4b84-80b8-6da5430816d5)
