### ISSUE TITLE
Change the appearance of tabs

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#11213]
- [ ] Use [Mantine Outline](https://mantine.dev/core/tabs/)
- [ ] If the user has tabs, the tile background should be white
- [ ] If the user has tabs, the tile border should change to `gray2`
- [ ] (!IMPORTANT) If the user has no tabs, the appearance of their dashboard should **not** be affected

<img width="806" alt="Screenshot 2024-08-21 at 10 06 09" src="https://github.com/user-attachments/assets/f2591065-b96a-4a2e-ad32-5e4f6aa4cd3b">

note: we're using this as an experiment to see what the white background will feel like

**Comment by inverts** [comment]
Is the `gray2` in the description here referencing the Mantine gray 2?
<img width="470" alt="image" src="https://github.com/user-attachments/assets/cb257cdc-b254-4ece-99c2-a30fd3025932">
Just checking since it doesn't look as dark as the example image in this issue description, but it is close to the same color as the tab border:
<img width="270" alt="image" src="https://github.com/user-attachments/assets/b1e9a902-7ea8-49a7-8d93-7909d26c065b">
The tab border is Mantine's `gray 3`.
