### ISSUE TITLE
Sometimes the sidebar doesn't open up until I've clicked on it several times

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#11288]
https://www.loom.com/share/1fd4de2ace5e4088a5a285994a558da4?sid=53587888-eaf6-4a8f-84e5-c00c33c0dd38

This is only when I have a query run and a table selected. Seems to fine if nothing has been selected. 

Also, when I collapse , there seems to be a little moment when the whole element disappears first. Im not sure if thats supposed to be part of an animation and its really slow, or if it just shouldn't be doing that at all.

**Comment by rephus** [comment]
@joaoviana any idea what is happening here ?

**Comment by joaoviana** [comment]
It's because the current implementation of `Sidebar.tsx`(the reusable component, not the sql runner one) doesn't keep mounted - We could consider a different component all together for this @rephus. I believe it shouldn't remove the elements from the DOM (or we could play with display, visibility) when the user collapses/expands the sidebar...

**Comment by PriPatel** [comment]
this was resolved in another pr by @joaoviana
