### ISSUE TITLE
There are issues on pages (login, register, invite) when i disabled login via password and use only SSO (OIDC)

### ISSUE THREAD

**Issue by nesh-ua** [lightdash/lightdash#11686]
I disabled password authentication (AUTH_DISABLE_PASSWORD_AUTHENTICATION=true), and use only SSO authentication (via own OIDC provider). And i think there are a few issues on some pages:

Login page:

Expected behavior: I expected  don't see: "email input", "continue button", "OR section" (because only SSO option is allowed)

Actual behavior:
* I see all of this elements on login page

Invite, Register pages:
Expected behavior: I expected to see only register via OIDC provider button

Actual behavior:
* I don't see any options

I fixed these issues locally. If you need, i can make PR?

**Comment by rephus** [comment]
This only happens if only OIDC SSO option is enabled, but it doesn't happen if you enable only google, or you add multiple SSO providers...

> export AUTH_DISABLE_PASSWORD_AUTHENTICATION=true

Only OIDC

![image](https://github.com/user-attachments/assets/3a96ba8c-4e24-4e51-b7a3-35cb095cd8f9)

Only Google
![Screenshot from 2024-09-26 09-00-42](https://github.com/user-attachments/assets/8fbe9e74-9215-472d-8d58-2d12afacae89)

Google and OIDC
![Screenshot from 2024-09-26 09-06-58](https://github.com/user-attachments/assets/e298f1f6-57ba-49ed-b9fb-cb72f8036b6c)
