### ISSUE TITLE
Changes to a dashboard aren't saved if you leave to edit a chart

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1209]
### Describe the bug

When you make some changes to a dashboard, then click on a chart within the dashboard and edit it, then return back to the dashboard, the original changes you made to the dashboard aren't saved. 

### To Reproduce

https://www.loom.com/share/98e93f664da649289ae366e0d24fac1f

### Expected behavior

Two things: 
1. Once you edit a saved chart from within a dashboard, it should return you to the dashboard (see this issue #1208)
2. Once you've returned to the dashboard, it should be in the same state as when you left it (i.e. the changes you made before leaving should still be there)

**Comment by ZeRego** [comment]
I think that expected behaviour is just going to bring a lot of problems since we will have to store the dashboard state in memory. When should we expire that memory ? What if the dashboard was changed in the meantime ? 

I think we should have a warning when trying to leave the dashboard with unsaved changes or open the chart in a new tab. 

The best ux will be to update the saved chart without leaving the dashboard. We could allow the user to update the basic chart configuration from within the dashboard.

**Comment by TuringLovesDeathMetal** [comment]
> I think we should have a warning when trying to leave the dashboard with unsaved changes or open the chart in a new tab.

@ZeRego this sounds like a good option for now!

**Comment by PriPatel** [comment]
If the user has unsaved changes to their dashboard, **_and_** they try to navigate to:
- another area of Lightdash (eg. go to Explores to edit a chart)
- refresh the page 
- another website

the user should see a warning modal. They are able to continue to navigate away from the dashboard, or stay on the page. If they stay on the page, they still need to hit `Save` to save their changes. 

<img width="831" alt="Screenshot 2022-04-04 at 10 38 19" src="https://user-images.githubusercontent.com/12776522/161517769-270c2974-c572-42ea-b004-bc63309729b1.png">

**Comment by rephus** [comment]
I'm trying to use special componens and browser events to capture navigation + refresh, I've been looking at various places, and people are using those. Both are using the browser default popup (it might look  different in different browsers) I tested opera and chrome. 
There are not very flexible and there are some limitations.

> Using <Prompt> to capture navigation  https://v5.reactrouter.com/core/api/Prompt/message-string
Doesn't allow change in the title , so it shows the URL 
![Screenshot from 2022-04-07 12-37-50](https://user-images.githubusercontent.com/1983672/162181526-65ff74d6-f3c0-4059-9087-6ecc9e4b1c69.png)

> Using window event listtener `beforeunload` to capture Refresh
I was not able to change the message (or title) from the popup, but documentation says it is possible...
![Screenshot from 2022-04-07 12-37-41](https://user-images.githubusercontent.com/1983672/162181768-6feb6f08-1ebe-4fea-9f65-8ea579c1bbe1.png)

what do you think @owlas @PriPatel @TuringLovesDeathMetal

**Comment by rephus** [comment]
Draft here https://github.com/lightdash/lightdash/pull/1700

**Comment by nathaliabj** [comment]
> https://v5.reactrouter.com/core/api/Prompt/message-string

@rephus I have found [this](https://shubhamverma.dev/how-to-create-a-custom-dialog-in-react-to-show-before-user-leave) and [this](https://michaelchan-13570.medium.com/using-react-router-v4-prompt-with-custom-modal-component-ca839f5faf39) options which would allow you to create a default component to display before the page unloads, however **it wont work if the page is reloaded it only works if you try to navigate away from some action in the page**, and because in modern browsers you are not able to customise this dialog, i really don't think we could have the best scenario in both worlds.

**Comment by rephus** [comment]
ok, so we can still customize the Prompt, but there is nothing else for the `beforeunload` I use to capture the reload...

**Comment by rephus** [comment]
This should be the modal to use in <Prompt> (when navigation happens) the refresh  action popup will have to stay as it is (browser default) 

![image](https://user-images.githubusercontent.com/1983672/162386468-88a96bcd-9328-4b4c-8a06-2645304d5a63.png)

@PriPatel what do you think ?

**Comment by rephus** [comment]
I don't think [this](https://michaelchan-13570.medium.com/using-react-router-v4-prompt-with-custom-modal-component-ca839f5faf39) option works, the article is from 2018, and it was using an undocumented feature, so the component has probably changed, I'm going to try with history.block
