### ISSUE TITLE
Long filter values break dashboard page layout

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#12336]
### Description

Very long filter values cause the dashboards to have a side-scroll and push the data zoom controls off the page

These filters should get truncated/overflowed.

<img width="1504" alt="Screenshot 2024-11-11 at 10 06 05" src="https://github.com/user-attachments/assets/ab2ba0dc-1567-444e-9341-ecc6db8a8480">

### Steps to Reproduce the Bug or Issue

1. Make a very long filter on a dashboard

### Cloud or self-hosting

None

**Comment by PriPatel** [comment]
@magnew Im not sure if we truncate or use a number of values. eg. what if the values are numbers?  I think that would annoy people? 
https://github.com/lightdash/lightdash/issues/6484
The suggestion was in this ticket here. Im thinking that this should be more 'width' based, rather than number of values based.  I suppose you could have one veryyy long value, and still have this issue?

**Comment by andrewdw** [comment]
I may have started working on this before reading the comments. In my draft PR I'm working on a width based system. 
It gets the page width via a hook and sets the max-width of the text. Still todo: visually showing the value is truncated, and dealing with it being aware of other elements nearby that make the page-width a bit smaller
