### ISSUE TITLE
Force users to update/notify them when new updates available

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#127]
Right now, if there is an update to Lightdash, it doesn't force you to update (and there can be changes that would make an older version non-functional). 

We should force you/notify you of an update if you try to launch an old version of Lightdash. 

E.g. if a user runs ` docker run -it -p "${LIGHTDASH_PORT}:8080" -v "${DBT_PROJECT_DIR}:/usr/app/dbt" -v "${DBT_PROFILES_DIR}:/usr/app/profiles" lightdash/lightdash`, then they would see:

```
⬆️ New updates available!

Please pull the latest version of Lightdash using 'git pull main', then re-launch 🚀
```

Then it would auto-crash/exit really nicely (if that's possible) :)

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal - Instead of showing this in the console - the suggestion is to show the current version of the app as well as if updates are available in the UI. 
This would also mean we're not exit-ing the app for folks who have Lightdash deployed in prod but aren't ready to bump versions yet.
