### ISSUE TITLE
Filtered dashboard tiles are tagged as filtered

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1275]
### Filtered tiles are tagged

Tiles that have a filter applied to them are tagged

<img width="355" alt="Screenshot 2022-02-02 at 13 44 27" src="https://user-images.githubusercontent.com/11660098/152165443-372e8a68-7f24-4c03-8861-76f7bc2bc8c0.png">

**Comment by ZeRego** [comment]
@PriPatel Should we use the filter icon in front of the name, like we do in the explore page sidebar ? And have that text has the tooltip for the icon.

**Comment by ZeRego** [comment]
@PriPatel makes sense.

My main concern is the placement since all tiles have a consistent header. This would make the header height different for charts. Could we have it after the chart title ?  
![Screenshot 2022-02-10 at 10 58 07](https://user-images.githubusercontent.com/9117144/153393278-11cdef88-b99a-4a46-a4db-4af0f70c6486.png)

**Comment by PriPatel** [comment]
@ZeRego I was hoping we get rid of the grey separator because it breaks the appearance anyway when the name takes up two lines. And yes, it can go below the header. 
![Screenshot 2022-02-10 at 11 05 07](https://user-images.githubusercontent.com/12776522/153394498-abc63cf0-7a74-4584-88c5-4fd821d63479.png)

**Comment by PriPatel** [comment]
@nathaliabj @ZeRego 
**For simplicity sake:**

We get rid of the grey divider in **chart tiles only.** Markdown and loom tiles should still have them.

We still keep as : 

![Screenshot 2022-02-10 at 16 24 30](https://user-images.githubusercontent.com/12776522/153451558-d1007eea-3b65-4236-9d74-c80229626910.png)
[Design linked here
](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=1639%3A43735)
I wanted to show exactly which filters were affecting the charts but I would need more time to figure out how to manage the long dimension names. I even thought that we could just show the user the filters when they hovered over "dashboard filter applied". I wanted to look at colour coding and adding numbers but again, I went down a hole trying to pick colours and finding the best way to format the pills. Too many questions for something that can be left simple. If we leave this as 'dashboard filter applied" for now, we can expand on it later when we have more feedback.
