### ISSUE TITLE
Caching Performance

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#12958]

**Comment by joaoviana** [comment]
## Suggested implementation

Cacheing on Postgres + base64 + TTL on the DB + date filters should be careful with how specific they are, so that the caching works. 
24h cache

TODO: 
- [ ] quick cache on postgres 
- [ ] have latency metrics to measure - if someone says that the query takes 20s, we should figure out why - core KPI
- [ ] which proportion of the query latency is warehouse vs us (on post-processing)

**Comment by almeidabbm** [comment]
Relates to #12969
