### ISSUE TITLE
figure out what we need to build to actually support dbt cloud

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#132]
We should be able to support dbt cloud users. 

Initially, this just means that they should be able to launch Lightdash locally (as well as in production?). They should be able to update their dimensions and metrics in dbt cloud and have that sync in Lightdash.

This ticket is complete if we have specced out the work required to start supporting dbt cloud users.

**Comment by owlas** [comment]
Nice @TuringLovesDeathMetal 

From looking at the API docs: https://docs.getdbt.com/dbt-cloud/api - it looks like the `manifest.json` is only updated after a run not a compile .

So it seems that if metrics are changed, we might only be able to detect that after someone hits run in dbt cloud.

I'll dig a little more

**Comment by owlas** [comment]
Was just chatting to @ZeRego and we also need to consider what features will be missing if we don't have access to the raw dbt project.

**Comment by owlas** [comment]
**dbt cloud feature requirements**

Here is everything we get from using `dbt` locally and what we'd lose by switching to a dbt cloud backend. I also suggest some workarounds, which we can turn into tickets

| feature | dbt cloud? | workaround |
|---|---|---|
|a `manifest.json` containing the whole dbt project definition, lineage, and lightdash `meta` tags | ✅ | |
|a `catalog.json` containing the whole database schema (column types) | ✅ | |
| a refresh action that enables us to update our representation of the users' dbt project | ⚠️  |  but this is a lot slower and probably we'll lose the tight "iteration loop" we get with lightdash today |
| ability to switch target database | ✅ | The way this happens locally (profiles.yml) and in cloud (job id) is different but essentially we can toggle a config variable to change which database and dbt project we are running lightdash against |
|the raw project files `.yml` and `sql` for the dbt project | ❌  | Could connect to the user's GitHub repo, or we disable relevant features (basically the "link to source" feature. we also lose the ability to quickly parse raw `yml` instead of waiting for dbt to compile |
| a function to execute raw queries on the users' data warehouse and get back rows | ❌  | we would need to build our own database drivers for each target data warehouse in order to run queries in our UI. This is a big feature that scales `O(n)` with the number of databases we want to support |
| credentials for the users database (aka `profiles.yml`) | ❌  | we would have to collect these with our own `yml` file or with  a new section of the UI (or both) |

**Comment by owlas** [comment]
We're back!!

Update: in dbt cloud you have two different major functions:

* Development IDE. You can edit text files and work on your dbt project including running any dbt cli commands and also executing queries through the dbt server. This works identically to when people are working locally with dbt with the current version of lightdash. **However** - these environments are typically connected to their development environment, so this isn't suitable for production (where we would need to query the production database). Moreover, this development server actually stops when you finish in the IDE. So we can only communicate with the dbt cloud sever while the user is actively using the IDE
* Production scheduler. For production, dbt will compile and run a project and we can get the artifacts back but doesn't provide us a server to use. But we can get credentials and build a profiles.yml file to run the server locally.

So we now have two different adapters for dbt cloud (which is not too dissimilar to running development vs. production with dbt locally)

**Comment by owlas** [comment]
Updating the table above in light of latest information: 

| feature | dbt cloud ide | dbt cloud scheduler | notes |
|---|---|---|---|
| a `manifest.json` containing the whole dbt project definition, lineage, and lightdash `meta` tags | ✅ | ✅ |
| a `catalog.json` containing the whole database schema (column types) | ✅ | ✅ | |
| a refresh action that enables us to update our representation of the users' dbt project | ⚠️ | ❌ | **ide** Unsure of how to refresh the server state. This seems to just happen automatically. **scheduler** will only update when schedule runs.|
| ability to switch target database | ✅ | ✅ | The way this happens locally (profiles.yml) and in cloud (account id and environment id) is different but essentially we can toggle a config variable to change which database and dbt project we are running lightdash against. We will be in sync with either the ide or the |
|the raw project files `.yml` and `sql` for the dbt project | ❌  | ❌ | Could connect to the user's GitHub repo. Otherwise simply disable relevant features. Today it's only the "link to source" feature. In future we would lose the ability to do a rapid refresh of the lightdash UI when you simply change a `meta` tag. We must always rely on a full `dbt compile` to get any small update |
| a function to execute raw queries on the users' data warehouse and get back rows | ⚠️  | ❌ | **ide** dbt cloud seems to implement a LIMIT 500 clause. We do similarly but might get some more unexpected results. **scheduler** we'll have to run our own dbt server but we can obtain the `profiles.yml` from dbt cloud |
| credentials for the users database (aka `profiles.yml`) | ✅  | ✅ | **ide** not needed since we have the query endpoint available. **scheduler** can obtain via api |
| always available | ❌ | ✅ | **ide** is only available when the user is logged in to a development session. **scheduler** latest manifest.json / catalog.json / profiles.yml always available via API |

**Comment by TuringLovesDeathMetal** [comment]
@owlas - this looks great!

I think this gives us pretty directly a set of tickets that we'll need to build on. 

I'd say we write these up as tickets and then some of them will require some more exploratory work to figure out if a workaround is possible, or what we can do if the feature is not possible to build as an option in dbt cloud. 

What do you think??

**Comment by owlas** [comment]
Yep I think the main tickets would be:

* Support integration with dbt cloud IDE (this is very similar to our dbt connector and pretty clear what minor changes are needed)
* Design integration with dbt cloud scheduler (this requires some more thought)

**Comment by TuringLovesDeathMetal** [comment]
interesting! I would have said that each feature would become a ticket 😅 (i.e. each cell in your table)
but that might be overkill...

**Comment by owlas** [comment]
@TuringLovesDeathMetal for dbt ide support, we only need to configure the existing adapter and then we'll get all the features out of the box. For dbt cloud we can probably introduce some tickets:

* add adapter for dbt cloud ide (this means we get manifest.json, catalog.json, and the ability to run queries without a profiles.yml, so that's all boxes ticked)
* add read-only adapter for dbt cloud prod (this is juts getting manifest.json, catalog.json, but we can't actually run queries)
* add ability for the user to specify a `profiles.yml`
* add run query to dbt cloud prod adapter

**Comment by TuringLovesDeathMetal** [comment]
sounds great! let's chuck em into tickets then :)

**Comment by owlas** [comment]
Done:
* #197 
* #198
* #199
