### ISSUE TITLE
Customised colour palettes for charts

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1572]
### Description: What is it?

Ability to establish a color palette that are the default for charts, including setting colors for grouping variables (in bar charts, for example).

### Problem: What problem does this solve?

As a data scientist, I want to make dashboards available to my colleagues that look polished (reflecting basic company branding) and that they would be comfortable sharing on their screen on a call with a customer.

### (Optional) Why: How do we know this is a real problem and worth solving?

As a Lightdash beta user, the ability to easily set brand colors would be on the "must-have" checklist if we were to pay for and adopt Lightdash as our main BI tool.

### What: Roughly, what does this look like in the product?

Somewhere in settings, I would be able to specify hex colors in a color palette that would be accessible in all charts and dashboards. Furthermore, I would be able to select default colors for charts, such that when I group by a field that has two values, it always uses our dark orange and dark blue, or with four values, uses a spectrum between our lightest and darkest blue, etc.

**Comment by TuringLovesDeathMetal** [comment]
Questions:

**Where would this live?**
I'd imagine something similar to Google Chrome or Slack, where in the `settings` space, there is a `theme` or `appearance` tab. This would hold all of the appearance settings (including things like #130 - dark mode). 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/31848148/159894385-9e06fb0c-5b01-405e-857e-b27ee9ed7ec6.png">
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/31848148/159894421-f2c5ed0f-9992-4a68-bc3a-654821a7b42b.png">

**Does it apply to all users? Do default pickers apply to all projects or just one?**
Yes. It applies to all users. 

I also think it should be an _**organization setting**_ instead of a project setting. 
If it's not too difficult to implement this as a project setting in the backend, then that would be great (in case folks want to have it at a project level later on...). i.e. in the UI, you set it at an organization level, but in the backend, it just sets the default for all projects in that organization (if that makes sense?) @owlas is that possible?

Also, because it's an _**organization**_ setting, we should make sure that we indicate this when you're changing it. 

I imagine that the `appearance` setting will have some org-wide settings, but also some user-based settings (e.g. do I want it to be in dark mode?). And, based on your permissions, you'd get access to some settings, but not all settings (e.g. only admins can change organization appearance settings).

@PriPatel not sure if there's a better way that you'd want to organize this/do this instead!

**Do we need permissions around it?**
Yes, only admins should be able to change organization appearance settings. 

**Can I override the default colours for a single chart/dashboard?**
Yes, you'd have the same colour changing options as we have now in the chart configs. So you could always adjust the default settings to be some other colours in any given chart. 

For fonts, I think we would not let this be override-able in the chart (for now). Maybe later...

**What _are_ the things I can pick?**
You should be able to select a default colour palette - this is 8 colours. 

You should be able to change each of the 8 colours individually. 

There should also be some way to revert back to the Lightdash default colours (I'd imagine eventually, this space will look something like the `slack themes`, where you can create a custom theme, but also pick other people's themes). 

You should also be able to choose the font style for your chart titles + chart properties (axes labels, legend, ticks, etc.). This includes the font + the size of the font.

If it's really difficult to implement the size of the font, then we should just do the style for now :)

**Comment by TuringLovesDeathMetal** [comment]
FYI, I've opened a separate issue for being able to use colour hues in the chart configs: https://github.com/lightdash/lightdash/issues/1579

Eventually, this could be included in hte chart config default settings, but for now it's a totally separate issue.

**Comment by PriPatel** [comment]
[Proposal for a v1 here!
](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=2326%3A43462) I have no idea how complicated any of this is technically but Ive given it a stab!

- User is able to replace the 9 default colours one by one in the settings panel.

- If there is one series, by default `Colour 1` will be picked. If there are two series, by default `Colour 1 `and `Colour 2` will be picked and so on.

- User can pick the default fonts (google fonts)  being used on charts. Im not sure about this - I think it needs more thought. If they want it applied to charts, surely they want it applied to dashboards as well? Otherwise they will have dashboards with branding that is half theirs / half Lightdash's.

**Comment by TuringLovesDeathMetal** [comment]
niiiiice! @PriPatel this looks great 😍
