### ISSUE TITLE
feat: add duckdb as DataSource

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#1585]
Adds Duckdb as an embedded, in-process OLAP db engine. Should also enable boiling data hosted version.

Allows for additional db in Duckdb, will allow users without DWHs to bring files or ones who want to try without needing to provide access. Should be potentially useful for demo on customers files for live demo.

https://github.com/apache/superset/pull/19317

**Comment by djayatillake** [comment]
@collin-luma https://lightdash-community.slack.com/archives/C039GAKTPMK/p1683406315668019

**Comment by Riezebos** [comment]
@djayatillake would it be possible to share the content of the slack link here for the people who don't have an account?

Support for duckdb would be amazing, it could make it possible to connect lightdash directly to parquet/duckdb files stored in s3. The SQL dialect is based on postgres which is already supported.

Furthermore, there is:
- https://github.com/duckdb/dbt-duckdb
- https://www.npmjs.com/package/duckdb

As a cherry on top, support for MySQL, sqlite and excel files are added for free :)
https://duckdb.org/docs/extensions/official_extensions

**Comment by djayatillake** [comment]
Which slack link?

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned. 

Lightdash only supports trusted adapters from dbt. This is because of previous experiences running into usage inconsistencies with non trusted dbt adapters. You can find the list of trusted adapters here: https://docs.getdbt.com/docs/trusted-adapters

We can reopen the issue once DuckDB becomes a trusted adaptor.
