### ISSUE TITLE
Set possible filter values from dbt accepted values tests

### ISSUE THREAD

**Issue by chadfl** [lightdash/lightdash#1995]
### Description: Accepted value Filters

DBT already has tests for accepted values. Lightdash could use that to pre populate pick lists for filters.

### Problem: 

When filtering on string fields the end user has to know what values to type in. Using accepted values, Lightdash could help them out. This is especially difficult when case matters, and the end user isn't a dbt/sql developer and aren't intimately familiar with the data. 

The current option is to run a query on that column to get distinct values in one window, and use the output in another window on a tile you are trying to build.

### What: Roughly, what does this look like in the product?

add filter. click in text box. picklist appears. click value. proceed.

**Comment by TuringLovesDeathMetal** [comment]
@chadfl cool! this sounds like an interesting idea. 

We actually already have auto-complete with our string filters, but with a bit of a quirk: you have to have the data in your results table to be able to filter on it (otherwise, we don't know what values are possible in your data warehouse - and we don't really want to run a `SELECT DISTINCT * FROM table` 🙃)

This sounds like a great addition to how we could make auto-complete work more often for filters. 

Do you write accepted values often for string fields in dbt? (e.g. do 50% of your string fields in a model have accepted values? or more/less?)

**Comment by TuringLovesDeathMetal** [comment]
@all-contributors add @chadfl  for ideas

**Comment by TuringLovesDeathMetal** [comment]
Fixed in #3210
