### ISSUE TITLE
I want more context on big number tiles and want to see how the stat compares to last week/month.

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2045]
<img width="787" alt="Screenshot 2023-03-21 at 17 15 34" src="https://user-images.githubusercontent.com/12776522/226688323-2f15e733-4dc5-42bf-b6cb-cdc049d77e8c.png">

### MVP requirements
**Big Number Chart config panel**:

- [ ] If the user has chosen a numerical field (metric, dimension, table calculation), show an additional option in the chart config panel : `Compare to previous row`. This can be toggled on and off. 
- [ ] The user should be able to choose between `raw value` and `percentage`.

**Big Number tile**:

- [ ] Show the comparison below the label. We can play around with sizing, placement, responsiveness etc.
- [ ] Icons : [arrow-up-right](https://tabler-icons.io/i/arrow-up-right) and [arrow-down-right](https://tabler-icons.io/i/arrow-down-right)
- [ ] Content:

  | Increase | Decrease | No change | Not applicable
-- | -- | -- | -- | --
% | +5% | -5% | +0% | n/a
Raw | +5 | -5 | +0 | n/a

**Comment by TuringLovesDeathMetal** [comment]
> In chart config, allow the user to choose what to compare with ( is it always a timeframe?)

I think you should just always compare the one row below it (doesn't really matter if it's a timeframe or not - that's up to you). 

^An example of where I'd want this without a timeframe: comparing two experimental groups. E.g. "Group A had 100 conversions. That's 20% more than group B" (where group A would be the first row, and group B would be the second)

There should also be a way of changing the label for the comparison

**Comment by JohnRomanski** [comment]
It may be easier to have the visualization always display data from two columns in the same row. You could use table calculations to determine the formatting of the second field, a net difference or a change in percentage.

**Comment by TuringLovesDeathMetal** [comment]
@JohnRomanski I don't think I'd use two columns as often as two rows. 

Typically, you'd be using comparison chart types for comparing over some time series. (e.g. last week's sales vs. this week's sales). 

Your date dimension will normally the dimension in your results table, and the metric you're comparing will be increasing/decreasing from one row to the next. 

Otherwise, you'll need to create a table calculation (like you said) to create another column which looks at the next row (or the _x_th next row) to compare it to the current value. 

^I guess this _**could**_ be more flexible? (since you might want to compare across products, or something that isn't in the same column). But I feel like the majority of uses are comparing the same column, so you'd be adding complexity to a majority of use cases to support a minority of more advanced cases 🤔

**Comment by JohnRomanski** [comment]
I think because Looker requires you to create a table calculation in most cases, and makes it super easy to do, I don't see it as being difficult. I know I can compare anything against what is in the same row.

In Looker we compare against _all kinds of things_, one of our favorite measures to compare is `P4WA` (Previous 4 Week Average, which helps us correct for non-seasonal spikes between weeks) which is based on a time series yes, but requires a table calculation. 

Here is a sample video of the interface I am used to:


https://user-images.githubusercontent.com/382382/171888000-e87af1ef-4723-4b65-b3ac-e34bae951ac9.mov

**Comment by PriPatel** [comment]
Still very relevant!

**Comment by PriPatel** [comment]
Very relevant, especially for Slack updates!
