### ISSUE TITLE
Hide the Headway icon on the 'Connect a project' page during onboarding

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2058]
When connecting a project, the headway icon is pretty distracting. The 'red' symbol makes me think that this is something super important but its not relevant to me at this stage at all.

<img width="1440" alt="Screenshot 2022-05-10 at 19 40 48" src="https://user-images.githubusercontent.com/12776522/167668927-517b8726-7d4e-4bbb-9cf7-d36f0de8566a.png">

**Comment by nathaliabj** [comment]
After a conversation with @PriPatel we agreed that this icon is pretty distracting however we feel it is still nice that the user is able to see whats new, maybe some people just cant bother to complete the onboarding but then they see a new feature that they would be super interested in and then that would persuade them to complete it? 

Because of the above, Pri will give it more thought on how to proceed, or at what point of the onboarding we want the headway icon to start showing.
