### ISSUE TITLE
Naming a table as a keyword causes an error in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2075]
### Describe the bug

If I name my table `order`, then BigQuery will throw an error when I try to reference the table name in a query (since it's a keyword).

### To Reproduce

Create a table called `order` 

try running a query that references that table by nicknaming it `order`

```
SELECT
CASE WHEN order.test > order.test1 THEN order.test

FROM lightdash-analytics.dbt_khindson.order AS order
```

### Expected behavior

We should quote identifiers with `

i.e. 
```
SELECT
CASE WHEN `order.test` > `order.test1` THEN order_model.test

FROM `lightdash-analytics.dbt_khindson.order` AS order_model
```

**Comment by owlas** [comment]
We should quote the identifiers like `AS `order``

**Comment by rephus** [comment]
This issue seems to be affecting other adaptors like `Postgres`: 

However in postgres we should wrap identifiers with ", not ` like in BigQuery

This works 
![image](https://user-images.githubusercontent.com/1983672/168541032-0b38824e-83d0-4581-ab59-b4fcb0fafbd2.png)

this doesn't ![image](https://user-images.githubusercontent.com/1983672/168541156-ced78f8b-6f41-43f6-a16a-4c36e1640326.png)

However I think the method is generic for all adaptors.. `buildQuery` ? Any ideas ? @ZeRego @owlas

**Comment by ZeRego** [comment]
@rephus There is a `getQuoteChar` method in `packages/backend/src/queryBuilder.ts` which should get the correct quote chart for each warehouse. Did you try this ?

**Comment by rephus** [comment]
no, let me try that, thanks
