### ISSUE TITLE
Add permissions for Jobs resource

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2107]
### Description: What is it?

Implement the following permissions for the jobs API

* Jobs with a `project_id`
  * Any user with view access to the project can view this job
* Jobs without a `project_id` should be given a `user_id`
  * Users with a matching `user_id` can see these jobs

**Comment by rephus** [comment]
I thi it makes sense to makes new `user_uuid` field `notNullable()` but we need to add a `defaultTo` because the `job` table might contain values already. 

I could make a request on the migration to users to fetch "one" of the existing users on DB and use that uuid as `defaultTo` 

Or I could simply set the field as `nullable()` 

What do you think ?

**Comment by rephus** [comment]
@owlas we should probably create another ticket for this milestone about making permissions per project, eg: `defineAbilityForOrganizationMember`

**Comment by ZeRego** [comment]
I would prefer the first approach and set the existing admin user as the owner of the existing jobs. 

I also propose the job only expose a generic error message to users with role VIEWER since the real error message could expose sensitive information. What you think ?
