### ISSUE TITLE
Results table should behave like cells 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#2149]
There have been some feature requests recently to do with the results tables and enabling functionality similarity to spreadsheets. Should the results table behave like cells? 

- it would make coming up with totals easier
- columns should be as wide as they need to be, not take up 100% of the width of the panel.
- it could make formatting easier (eg. conditional formatting)
- the user could resize columns
- it could make deleting / adding actions to columns and rows easier and more intuitive.

Discussion tag because this might be controversial?!

**Comment by JohnRomanski** [comment]
I don't know which part of the described behavior is _cell behavior_, but I do agree that the table should behave more like a modern web table and more like Looker.
- there should be Row Totals and Column Totals available and possible for all Measures (which Looker offers)
- there should be conditional formatting for each column in the table, which should also be applied to the chart (which Looker offers)
- not to beat a dead horse, but Looker offers a gear at the top of each column that allows a lot of actions: you can 'remove from table, filter, start a table calc based on column, remove column from the visualization, copy values, and go to the LookML definition' (this moves the control of visibility of the series out of the chart config where it is now of course.) 
- For date columns there is an option that allows you to 'Fill in Missing Dates' so that you can normalize your charts and highlight missing data, as well as include future dates for forecasting purposes. (past 90 days and NEXT 90 days to use existing data for a linear regression to predict future values

**Comment by PriPatel** [comment]
Relevant - Will be looking at this soon
