### ISSUE TITLE
When a user first launches Lightdash, they need to sign up

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#223]
https://www.sketch.com/s/2488cd5e-59cf-4a9a-ad87-54720ce950fc

When a user first launches Lightdash, they need to submit their:
- email address
- first name
- last name
- password
- company name

We then:
- generate a unique, global `user_id` (this should be random - i.e. not generated from email address or anything)
- save their data in a PostGres db
- trigger an event to BigQuery (see #228 )

**Comment by owlas** [comment]
Requirements:
- [ ] Database: postgres?
- [ ] Node db library: knex? raw?
- [ ] Auth (just email password initially)
- [ ] Reset flow or email confirm? (needs mail server)

**Comment by ZeRego** [comment]
How we going to persist this data when users want to update Lightdash image ? using docker volumes ?

https://docs.docker.com/storage/volumes/
https://www.jajaldoang.com/post/run-postgresql-database-with-docker/

Do we want to have a Lightdash config to disable authentication ? I can see this being useful for local development and the demo/PR environments. We can still create a uuid for anonymous tracking.

>  Reset flow or email confirm? (needs mail server)

I think this is a little bit out of scope and we might need to explore other options beside setting up a mail server. 
Right now we could just provide instructions on how to clear/reset the DB. 

>  Database: postgres?

What are your thoughts on SQLite ? https://www.sqlitetutorial.net/what-is-sqlite/

Looks like a good fit:
- our DB is going to be fairly small and simple
- database is usually contained in a single file on disk
- does not require a server to run, unlike Postgres and others

**Comment by owlas** [comment]
> How we going to persist this data when users want to update Lightdash image ? using docker volumes ?

This is exactly why would use an external database over sqlite attached to the lightdash docker container. In dev mode it's a bit of overhead to run postgres but nothing compared to trying to get sqlite to work well in a production environment.

As for persisting when people run locally, you would run postgres in docker via docker compose, which creates a volume for you. In production, the user would need to supply their own postgres database (e.g. Cloud SQL in GCP)

As for migrations, we can trigger them manually in the lightdash (or dedicated container) or have them run automatically in the entry point.

> I think this is a little bit out of scope and we might need to explore other options beside setting up a mail server.

Yep sounds good

> Do we want to have a Lightdash config to disable authentication ? 

That's a good option. We could also accept the admin user details in lightdash.yml rather than using the UI, if somebody would prefer
