### ISSUE TITLE
Cannot copy and paste multiple filter values

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2298]
### Description

Some of the filters accept multiple values but I can't copy those values from the field or paste values. Ideally I'd like to paste multiple values from csv/excel that are comma-separated values or values that are separated by a new line.

![image (13)](https://user-images.githubusercontent.com/11660098/171411507-9b1104db-67d1-445f-a4e2-33aeef0279c8.png)

https://www.loom.com/share/6da14533131c459bb51cb5ac246e4fdd

### Acceptance criteria

- [ ] I'm able to copy-paste a list of comma separated values into a filter for `includes`, `is equal to` and they appear as separate filter values (e.g. `test, test1, test2` would appear as `test` `test1` `test2` each as an entry in the filter)
- [ ] I'm able to copy-paste a list of new-line separated values into a filter for `includes` or `is equal to`

**Comment by JohnRomanski** [comment]
I am not sure this is a bug, maybe this should be considered more of a feature request.

The filters are not simply text strings, but divs that are highlightable and selectable via the keyboard shortcuts.
Right now, you can not select multiple values. What would you be copying? 

Also since Looker hasn't found a way to do this, I think that this is more of a 'feature request' and lower priority one. (since there is an easy workaround.)

**Comment by ZeRego** [comment]
+1 for JohnRmanski comment. Feels more like a feature request than a bug and not sure how often people need to copy the values from the filter 🤔 

Btw, the input already supports pasting multiple values separated by comma `,`. We can easily support more separators like `;` if needed.

**Comment by ZeRego** [comment]
Someone filled a similar [feature request](https://github.com/palantir/blueprint/issues/5275) for the UI library we use
