### ISSUE TITLE
Metrics in the UI should be called Measures (discussion)

### ISSUE THREAD

**Issue by JohnRomanski** [lightdash/lightdash#2302]
### Description

Metrics in the UI should be called Measures

 (discussion) but I can't access that label.

### Reasons

- dbt Labs now has something called Metrics, which is not quite the same
- Looker calls them Measures, Looker users who migrate over will be confused
- Lightdash already calls them measures in the YAML and in intro video

![Screen Shot 2022-06-03 at 9 54 52 AM](https://user-images.githubusercontent.com/382382/171868539-e380e225-20e5-4f72-bf69-c3a8eeb1ba19.png)
 
![6ih3ne](https://user-images.githubusercontent.com/382382/171868482-60b1b674-08d0-499b-8fa4-4ef360c9e17a.jpg)

**Comment by TuringLovesDeathMetal** [comment]
haha -  I think it's a bit subjective (and that video was actually recorded _**right**_ before we changed it to metric!)

I have a strong feeling that Looker + Power BI called them `measures` because Tableau called them `measures`...
And who knows why Tableau called them measures 🤔 

Metabase uses `measures` for raw, unaggregated data (e.g. `revenue`, but as a dimension). And they use `metrics` as the term for an aggregation applied to a `measure`: https://www.metabase.com/glossary/metric. So they're using `metric` for the same computation as we do :) 

AirBnb's internal metrics store (Minerva) uses the terms `metrics` and `dimensions` ([source](https://medium.com/airbnb-engineering/how-airbnb-achieved-metric-consistency-at-scale-f23cc53dea70#:~:text=To%20date%2C%20we%20have%20more%20than%2012%2C000%20metrics%20and%204%2C000%20dimensions%20in%20Minerva%2C)). 

Also, if you search `metrics layer`, you get way more hits than `measures layer` (because a `measure` is really just a Tableau, Looker and Power BI thing 😉)

^as you might be able to tell, we did think about this quite a bit when we decided it! 😅 So unless we get a bunch of feedback that users "don't understand what a metric is", then I think we'll probably keep it as-is :)

**Comment by TuringLovesDeathMetal** [comment]
Also, a `metric` in the Oxford dictionary is defined as:

```
(in business) a set of figures or statistics that measure results.
```

But there's no similar, commerce/business-related definition for `measure`...

```
a standard unit used to express the size, amount, or degree of something.
```
