### ISSUE TITLE
y-axis layout dropdown doesn't show active field

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2456]
### Description

x-axis shows all 3 fields, y-axis shows only 2 fields:

<img width="329" alt="Screenshot 2022-06-16 at 14 56 36" src="https://user-images.githubusercontent.com/11660098/174088438-e9548c70-6c0c-4994-995e-6ca4aa00cdea.png">

<img width="350" alt="Screenshot 2022-06-16 at 14 56 27" src="https://user-images.githubusercontent.com/11660098/174088450-9398c7cc-4942-463b-b129-d5dc1feef296.png">

**Comment by nathaliabj** [comment]
@owlas I think this was on purpose by design. 
@PriPatel Please correct me if i'm wrong, but it think the purpose of this was to be able to select any field on `x axis`, and the `y axis` will only have available the rest of the fields. so we avoid having `x & y axis` with the same label, if you change the `x axis` the the previews one becomes available on the `y axis`.

**Comment by PriPatel** [comment]
Hmmm
Im not sure anymore! I feel like that was the original design but we changed it to reduce the amount of clicks. So I *think* this is a bug.
