### ISSUE TITLE
Left-click to get table value actions

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2472]
### Description

In the explorer table, I can right-click on a value and it'll show this context menu. It's very hard to find. Let's make it more prominent:

* on-hover -> underline the value / use `cursor: pointer` 
* on-left click -> show the context menu when left-clicking as well as right-clicking
* on-hover row -> make the whole row look selected when hovering over a row (not sure on the best approach here, probably making it a slightly darker shade?)

<img width="278" alt="Screenshot 2022-06-20 at 09 39 30" src="https://user-images.githubusercontent.com/11660098/174561344-aadab574-06f8-477b-95dc-3840302c59dc.png">

**Comment by PriPatel** [comment]
Note - Users might want to copy and paste values from the table and this could get in the way!

**Comment by nathaliabj** [comment]
Needs a bit more research on how to make the context menu more prominent

**Comment by 12ian34** [comment]
I'd be wary of hijacking the right-click action even in web apps. This means that we are assuming all the actions supported by right-clicking trump any action the user might want from the standard web page right-click context menu. It works in Google Sheets because it's basically Excel in a web page and that's what users are expecting. Since Lightdash is a web app with multiple panels here and there, hijacking right click might not always be what the users expect.

Not saying we shouldn't do this, just saying perhaps we need to think about any negative implications.

**Comment by owlas** [comment]
Closing for #2785
