### ISSUE TITLE
existing doc blocks aren't recognized by the CLI tool

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2562]
### Description

I have docs with existing doc blocks:
```
columns:
  name: organization_id
  description: "{{ doc("organization_id")}}"
```

And I get this prompt:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/31848148/175882508-71f6df00-2b58-4024-8699-620420af235d.png">

### To Reproduce

1. Create a doc block reference that doesn't use Lightdash's doc block formatting (i.e. _**not**_ like: `"{{doc(\"user_id\")}}"`)
2. Run `lightdash generate`

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal we ask that question if the description is defined, independently of its content.

You'r suggesting we don't override the description if it is a doc block ?  We could write a regex to detect it but how many variations are there of a doc block ? 🤔

**Comment by owlas** [comment]
Oh this is a bit annoying. So the problem is:

1. I already have an existing doc block like `doc('hello')`
2. Lightdash checks for docs blocks in this exact form `doc(\"hello\")`
3. So it will ask if you want to replace `doc('hello')` with `doc(\"hello\")` ?
4. After this it will never ask again

I think in the initial example, the doc block won't actually compile: `"{{ doc("organization_id")}}"` does that actually work?

**Comment by TuringLovesDeathMetal** [comment]
Looks like it was working!
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/31848148/175948645-a4450464-84de-4a8a-8c48-064f098ccf10.png">

The other way of writing doc blocks (as suggested in dbt's docs) is: `'{{ doc("table_events") }}'`

Is there some way to check all three variations of this?

**Comment by TuringLovesDeathMetal** [comment]
sure! That sounds great!

Slightly more rigorous could be checking: `{{<space>?doc(` + anything + `)<space>?}}`
