### ISSUE TITLE
[epic] sql runner equivalent capability and ability to save these

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#261]
- [x] #703
- [x] #704
- [x] #705
- [x] #706
- [ ] #707
- [x] #708

**Comment by owlas** [comment]
For reference: https://docs.looker.com/data-modeling/learning-lookml/sql-runner

**Comment by owlas** [comment]
Moving off the project until we finish the design.

We need to make quite a few UI changes for the sql-runner view in the frontend.

Will add designs below and breakdown this issue into smaller pieces.

**Comment by TuringLovesDeathMetal** [comment]
Here's the initial design for the SQL runner:
https://www.figma.com/file/vqno5NlvX29bAcaHFmRDIL/SQL-Runner?node-id=20%3A17

I've also added interactions so I _**think**_ you can play through this and see what's being clicked to generate which page.

Three things:
1. I've updated the nav bar to include `browse` and `explore`. Eventually, it'll also have `develop` and `admin` 
2. The V1 of this is without visualizations. This is because we'd need to be able to identify dimensions vs. metrics in the raw SQL query and apply those types to the results in order to get visualizations. This could be easy? But I'm not sure...so, for V1, we'll just keep it as straight up SQL.
3. While this is straight up SQL, we shouldn't be able to save these queries. But, we should be able to copy-paste this SQL easily into somewhere else. If we're able to save these, it would be the exact same as the [dbt `analyses` feature](https://docs.getdbt.com/docs/building-a-dbt-project/analyses). Since Lightdash is built from your dbt project, I think copying this feature would be confusing: "Where do I put my analyses? In the saved Lightdash folder? In dbt? Why aren't they the same thing?"  - we'll need to think about this some more.
If/when we add charts to the SQL runner, then we should be able to save these as `saved charts`.

**Comment by djayatillake** [comment]
looks good, one of the things I don't like about the way Looker does this is: when you use a sql runner to make a temp explore with chart etc, if you then want to slightly change the query you lose the whole explore; it would be great if we could avoid this.

**Comment by owlas** [comment]
@djayatillake for example, if I rerun the query and it returns the same column names + types, then the chart shouldn't be reset?

**Comment by djayatillake** [comment]
it's more if you edit the query but still have the same columns or same columns plus some additional ones, then the you have to recreate the temporary explore and any dimensions and measures you've made.
