### ISSUE TITLE
Chart flickers when opening series configuration

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2737]
I'm getting the chart flickering every time I open the chart config tab, I guess this is because of re-rendering? https://www.loom.com/share/0e03fb412e6242259199e778978cdc86

**Edit** this seems to come from the series re-rendering. When I switch between tabs in the config panel, it flickers again whenever I switch to the 'series' tabs, switching to the other tabs doesn't do anything

_Originally posted by @owlas in https://github.com/lightdash/lightdash/issues/2733#issuecomment-1188960810_

**Comment by rephus** [comment]
My fix for this Issue will not fix the issue  #2723 , some backend requests are happening when we click stuff, I fixed the request for this issue ( `/orgs` )  but there are a few others (like /orders and /compileQuery) . It could also be not related with backend requests, so we need to keep investigating.

**Comment by rephus** [comment]
Some context from closed issue https://github.com/lightdash/lightdash/pull/2747

From @owlas: 

I actually don't mind the many calls to /org, I doubt it affects performance. It's more that the refetch triggers the chart to flicker. I don't want to pivot this issue into trying to stop all the /org fetches. By fetching constantly we know we always have the most recent data when each component loads, which is much simpler than trying to manage a cache of the state around the app

From: @ZeRego
Some component in the chart config must be using the useOrganization hook instead of using the data from the useApp hook. thinking
