### ISSUE TITLE
Build a Slackbot for sharing Lightdash links in Slack

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2776]
-Similar to [how Metabase does](https://www.metabase.com/docs/latest/administration-guide/09-setting-up-slack.html#create-your-slack-app) the setup for Slack
    - Setup your own bot and connect this to your Lightdash instance + your Slack instance.
        - This means that the Slackbot is part of the app (instead of being a separate slackbot app)
        - ^If we have references to the Slack Bot in the app, it would be weird to not include it as part of the core app (which is why I think this is a better idea than making a hosted Lightdash Slackbot like [Looker](https://help.looker.com/hc/en-us/articles/360023685434-Using-Lookerbot-for-Slack)
       
- To connect Slack, you’d go to `settings`, then under `organization settings`, you’d have `slack`
    
<img width="337" alt="image" src="https://user-images.githubusercontent.com/31848148/180757806-a1d28de4-4cbc-4d1c-b89a-cb4245169e82.png">
    
- This would bring you to a connection page like this:
    - Need to think about how we’d guide users through the “building a Slack app” - would we just send them to the docs?
    
<img width="485" alt="image" src="https://user-images.githubusercontent.com/31848148/180757903-11f43f43-f856-467a-8989-7ed09bce6f20.png">
    
- Clicking `open slack apps` brings you [here](https://api.slack.com/apps):
    
<img width="683" alt="image" src="https://user-images.githubusercontent.com/31848148/180757949-86e4c765-47fe-4be9-b04a-9aae7dd4d66f.png">
    
    - Select `from an app manifest`
      
<img width="385" alt="image" src="https://user-images.githubusercontent.com/31848148/180758076-069cb5bc-e8a5-43cf-80a7-e5aa0efa8d40.png">
        
    - We give them the manifest to put in here:
        
<img width="342" alt="image" src="https://user-images.githubusercontent.com/31848148/180758122-dc901599-467f-4388-be17-c2378a816b3d.png">
        
- Initially, this Slackbot would just allow for Lightdash links to be unfurled in Slack (like GitHub or other apps:)
    
<img width="578" alt="image" src="https://user-images.githubusercontent.com/31848148/180758160-99a5181c-1ef1-4672-bc7a-c81da1918f42.png">
    
- The unfurls would need to:
    -  show the ***entire*** chart/dashboard. —> reason being: I don’t want to have to login to Lightdash to be able to see what you’ve shared. What if I don’t have a Lightdash account?
    - have a link to the chart/dashboard you're sharing
    - If it's a shared chart/dashboard, then the title of the saved chart/dashboard would be included in the message title
    - if it has a description, include the description

**Comment by rephus** [comment]
Ok, this seems to be a simple way of doing server-side rendering, without adding too much code or dependencies to lightdash

## Add new chrome headless docker container 

```
  browser: 
    image: browserless/chrome
    restart: always
```

## Add puppetter npm repo to backend

```
"puppeteer": "^18.0.5",
```

## Add backend endpoint 

```

apiV1Router.get('/screenshot', async (req, res, next) => {
    const browser = await puppeteer.connect({ browserWSEndpoint: 'ws://browser:3000' });
  const page = await browser.newPage();
  await page.goto('http://lightdash-dev:3000/register', {waitUntil: 'networkidle0'});
  //const html = await page.content(); // serialized HTML of page DOM.
  const imageBuffer = await page.screenshot({path: 'screenshot.png'});

    res.writeHead(200, {
        'Content-Type': 'image/png',
        'Content-Length': imageBuffer.length
        });
        res.end(imageBuffer); 

        await browser.close();

});
```

## Returns this image

`http://localhost:3000/api/v1/screenshot`

![image](https://user-images.githubusercontent.com/1983672/191942770-4f74fcb5-472b-4baa-9485-536b3951916a.png)

## Things to do

- [ ] Authentication, bypass credentials or tokens to be able to access private pages 
- [ ] Test agains dashboards 
- [ ] Wait for charts to load 
- [ ] Resolution, adjust size of browser
- [ ] Upload image to google storage or similar ?
- [ ] Slack API for sharing images 

```
requests.post("https://slack.com/api/files.upload", 
        params={
            'initial_comment': text, 
            "channels": channel, 
            "file": "image.jpg" 
        } , 
        files= {'file' : (image, open(image, 'rb'), 'jpg')},
        headers={"Authorization": f"Bearer {settings.SLACK_BOT}"  })
```

**Comment by ZeRego** [comment]
@rephus I think that approach is going to require a few hacks and workarounds since we only want to screenshot specific parts of the app and not trigger page events etc. 

Would be great if we could just render specific components in the BE with `react-dom/server` and then screenshot it with something like `html2canvas`. 
Looks like people have been exploring this approach [here](https://stackoverflow.com/questions/54430332/how-do-i-take-a-screenshot-of-a-react-component-without-mounting-it-in-the-dom)

**Comment by rephus** [comment]
Does not `react-dom/server` require a big refactoring to work ? at least sharing the components between the backend and frontend, and maybe changing the way they are rendered... 

I can figure out how to block trackers on puppetter, I don't think we need to implement any more hacks. And instead of taking the screenshot of the whole page with puppetter, we can extract the HTML and then use `html2canvas` like you suggested , or just cropping the image to remove the navbar or similar.

My main concern about using headless chrome is performance,

**Comment by ZeRego** [comment]
> I've never used read-dom/server. Does not react-dom/server require a big refactoring to work ? at least sharing the components between the backend and frontend, and maybe changing the way they are rendered... Do we need to wrap the whole ?

I was thinking about using mock providers and since we are printing specific components with no interaction I don't think it would trigger any event. But I agree this might involve some refactor but only with this investigation we would find out it's size. 

> Is wrapping a component that makes a request on the backend not going to trigger the same page events anyway ?

Good question I suppose we would need to refactor the components to be "pure/dumb". They would get all the data via props/provider instead of using hooks that fetch data via API. This way we can hydrate the components when rendering them on the server. Probably no work for the chart component but a bit for the dashboard page. 

> I can figure out how to block trackers on puppetter, I don't think we need to implement any more hacks.

But not the ones from the backend. 

Also, what authentication are we going to use in puppeteer since it's going to be a slack bot making a request ?
@TuringLovesDeathMetal What happens if a user that has no access to a dashboard posts a link to that dashboard ? how will the bot know it can't render the image ?

**Comment by TuringLovesDeathMetal** [comment]
> @TuringLovesDeathMetal What happens if a user that has no access to a dashboard posts a link to that dashboard ? how will the bot know it can't render the image ?

I would expect the dashboard or image to render (no matter who sends the link)

Looking into other tools, that's how it's done elsewhere 🤔 I guess the logic is that someone could just screenshot something and send it to you if they wanted to. So for you to hack this system, you'd have to know the URL for a dashboard or chart you wanted to see that you didn't have access to (which should be hard because you won't be able to see charts/dashboards you don't have access to in the app).

**Comment by ZeRego** [comment]
@rephus @owlas Right now there is a blocker when using using react-dom/server to do server side rendering since the lib we use to display echarts `[echarts-for-react](https://github.com/hustcc/echarts-for-react)` doesn't seem to support server side rendering. 

Opened a ticket: https://github.com/hustcc/echarts-for-react/issues/506

**Comment by rephus** [comment]
@ZeRego let's unblock this. Should we then start building this without react-dom/server until this blocker is fixed ?. I think it should be easy to migrate. 

So we can be using chrome-headless and puppetter as I suggested, we can use `html2canvas` instead of taking a screenshot of the page, filtering only the `div` we want to share.
