### ISSUE TITLE
Can't set password after registering with social login

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2846]
### Description

If the user accepts the invite using google/okta, it gets an error when setting a password.

### To Reproduce

Steps & screenshot/gif/loom to reproduce the behavior
1. accept invite with google 
2. Click on settings
3. Click on password
4. Set new password
5. See error

<img width="1679" alt="Screenshot 2022-08-03 at 14 44 10" src="https://user-images.githubusercontent.com/9117144/182623693-11d95aeb-f179-440f-8c52-6247a4c7ce48.png">

### App Version

0.198.0

**Comment by rephus** [comment]
Should we disable the `set new password` field entirely ? or what /cc @owlas

**Comment by owlas** [comment]
Yes I think we should hide it. 

If they have emails configured, we should give the option to trigger the password reset flow. That way we at least ensure the user has access to the original email address on the account, instead of letting them add a random password.

So scenarios:
* If password auth is disallowed -> hide
* If password auth is allowed and password already exists -> allow user to use form
* If password auth is allowed and password does not exist and email configured -> password reset flow
* If password auth is allowed and password does not exist and email is not configured -> hide the config

What do you think @rephus ?

**Comment by rephus** [comment]
Will `password reset flow` hit the same error from this issue ?

**Comment by owlas** [comment]
Discussed offline:

Implementing a better UX for this (above) was some effort - and this fixes the bug for now.
