### ISSUE TITLE
Customise range of x-axis

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2943]
### Description

On a cartesian chart, I can't customise the x-axis range. Although I can customise the y-axis range. 

### Acceptance criteria
Miro sketch: https://miro.com/app/board/uXjVNFeuOjE=/?share_link_id=690462604539

- [ ] There is a new toggle added to the `axes` part of the chart configuration called `auto x-axis range`
- [ ] By default, this is toggled on and hte behaviour of the x-axis is like it is today
- [ ] if you toggle it off, then you can set the min and max values of the x-axis
- [ ] This toggle _only_ appears for x-axes with the type `date/timestamp` or `number`. 
- [ ] If the x-axis is a date or timestamp, then clicking on the input field opens the date picker
- [ ] If the x-axis is a number, then you can click ont he input field and just manually enter a number (just like how it is with the y-axis picker today).

**Comment by TuringLovesDeathMetal** [comment]
What if you could limit the rows selected from your results table in your chart? 
Or, add a filter to the values on the x-axis? 

Also, I guess if we customized the axis range, this would only work for numeric and date types? (not categorical)

**Comment by ZeRego** [comment]
Here is an example where this feature is useful.

> Josiah McDonald
  [19 hours ago](https://lightdash-community.slack.com/archives/C03MG2VTR08/p1675716307216639)
I'm working on visualizing a metric with a 7 day lag -- is there a way to hide part of a visualization without filtering it? Right now the first 7 days of my graph are missing because I'm using a lag function.
<img width="505" alt="image" src="https://user-images.githubusercontent.com/9117144/217287662-b3538ff4-0737-4107-84c4-44d37872bfaa.png">

**Comment by rephus** [comment]
This has been requested again

**Comment by ceik** [comment]
Also ran into this issue today. Filtering (as kinda implied above) did not work. I was able to work around it by turning the dimension into a date, but that only works in this special case.

![image](https://github.com/lightdash/lightdash/assets/7529722/52dec9a9-2fcc-4e23-bca3-8daee9e2ea65)

**Comment by rephus** [comment]
This would also allow customize the range so the weird wide barchart doesn't go out of the axis https://lightdash.slack.com/archives/C0415AUACGY/p1701994842624749
