### ISSUE TITLE
delete an organization in Lightdash

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2989]
### Description

I'd like to delete my organisation and all users associated with it. 

Since users can only join one org currently, it's easy to get stuck if you accidentally create a new organization when signing up instead of accepting an invite. 

This will allow users to delete their account and their organization and go back and accept the invite

Only org admins can do this.

- [ ] add this in the docs

**Comment by PriPatel** [comment]
![Screenshot 2023-01-10 at 12 23 06](https://user-images.githubusercontent.com/12776522/211550252-102e526b-a2a3-4e2b-8947-bfc265774f45.png)

**Comment by rephus** [comment]
@owlas What kind of documentation you had in mind ? https://docs.lightdash.com/

- Something in `Users` : How to delete your user and organization
- Something in FAQ: What happens if you can't accept invite because you already have an user
- Some new category about `Organisation` and how to delete them
