### ISSUE TITLE
Add `developer` role

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#3111]
### What problem does this solve?

Having a project and organization role type with access to all Lightdash features and only access to curated data.

### Proposed solution

Action | Project Admin | Project Developer | Project Editor | Project Viewer
-- | -- | -- | -- | --
View charts and dashboards | ✅ | ✅ | ✅ | ✅
Run metric queries | ✅ | ✅ | ✅ | ✅
Create/edit charts and dashboards | ✅ | ✅ | ✅ | ❌
Create/edit metrics<sup>1</sup> | ✅ | ✅ | ✅ | ❌
Run SQL queries | ✅ | ✅ | ❌ | ❌
Invite users to project | ✅ | ❌ | ❌ | ❌
Manage project access and permissions | ✅ | ❌ | ❌ | ❌
Delete project | ✅ | ❌ | ❌ | ❌

<sup>1</sup>not sure about this one, does it mean **Create/edit _custom_ metrics**?

### Alternative solution

Making it possible for Organization Admin to create and edit Project roles.

**Comment by TuringLovesDeathMetal** [comment]
Wow, what a table 🤤 

>1not sure about this one, does it mean Create/edit custom metrics?

Yep! I'll update the docs to make this more clear 👀 

I feel like with this new developer role, there would also be some limitations in using the CLI tool (e.g. right now, anyone can do `lightdash deploy` and deploy their local dbt project to their Lightdash project...we'd probably want this to be limited to developers)

**Comment by Martin-Carlsson** [comment]
@TuringLovesDeathMetal 
I agree, plus I don't think that other people than developers or admins would use the CLI.

**Comment by TuringLovesDeathMetal** [comment]
Cool @Martin-Carlsson!

Priyanka, our designer, did a bit of a teardown of the permissions flow last week. This feels like it'd fit nicely in with some of that work.

To be transparent about timelines: we're pretty crammed for this quarter (until start of October) building [scheduled sharing in Slack](https://github.com/lightdash/lightdash/milestone/47), [updating the CLI](https://github.com/lightdash/lightdash/milestone/49) and a bunch of other "making things nicer" changes.

But, I want us to give permissions a bit of a revamp starting next quarter because there's a bunch of great stuff in [this milestone](https://github.com/lightdash/lightdash/milestone/54) and I think that having a `developer` role would fit nicely in there. 

Is this an issue that's blocking you? Or could you wait until October for it?

**Comment by Martin-Carlsson** [comment]
@TuringLovesDeathMetal 💪💪💪

No rush here. For now this is only nice to have. We will manage permissions via projects.

**Comment by TuringLovesDeathMetal** [comment]
amazing! good to hear it's not a blocker - but will definitely keep you updated on the progress of it :)

**Comment by hamzahc1** [comment]
I really like this set of permissions! I think this maps really well to the real world and jobs that folks want to carry out.

**Comment by TuringLovesDeathMetal** [comment]
Hey @Martin-Carlsson just double checking here:

we've removed the `show hidden tables` button since this issue was opened. So now, it looks like the only difference in permissions between an `editor` and a `developer` is having access to the SQL runner.

Is this correct? Or were there other permissions that you would expect to be different between the users? 

I think the only other thing I'd add would be: only developers can run `lightdash deploy`

**Comment by suebeet** [comment]
Hi @TuringLovesDeathMetal,

I have couple comments regarding this (not sure if Oliver had a chance to convey my message or not yet).

1) The _permission management_ is now something that is blocking us, so it is not anymore "nice-to-have"

2) I looked at the table we created and maybe we need a little extra level of granularity
- Reg. "Project Editor": Is it possible that this level of user would be only able to create and edit their own dashboards, but not the once created for "all"? As in, we will have some dashboards, that should only be editable by "Project Admins" and "Project Developer", so we would not have to be worried, that someone will edit it :) 

- Reg. "Project Viewer", could we have a one more permission level, where the user would only see selected dashboards, but not all and definitely not explorers?

**Comment by hamzahc1** [comment]
> Reg. "Project Viewer", could we have a one more permission level, where the user would only see selected dashboards, but not all and definitely not explorers?

@suebeet - for the above, would this be solved with Space-level (i.e. folder) permissions? e.g. if you placed the necessary dashboards into a Space and gave folks Viewer only permissions on that Space (i.e. folder), they would only see the dashboards available in that space.

**Comment by suebeet** [comment]
Hi @hamzahc1 , yes that could work. BUT can we make sure that the drill-downs will be limited for the space level viewers?

**Comment by thomas-gamurs** [comment]
+1, this additional role would work perfectly for our use case to allow people to have edit permissions but not be able to view sensitive data in our warehouse in the sql runner!

**Comment by owlas** [comment]
As a quick fix, I propose we remove SQL Runner access for Editors and only make it available to Admins. 

Our data from the hosted Lightdash instance shows that very few users use the SQL Runner. Although I can't drill into how many of the queries were executed by admins vs. editors (we don't capture this data today), there are relatively very few queries using the runner. So this seems like a security risk that isn't providing a big UX benefit for most people.
