### ISSUE TITLE
Add a few ms before Add filter disappears

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#3113]
### Description

Add a few ms before **Add filter** disappears.

### What problem does this solve?

The **Add filter** menu disappears very fast, so you often don't get to click on it.

https://user-images.githubusercontent.com/7769335/187631351-976f10a3-8c05-4db6-9baa-a93b1ad2a584.mov

**Comment by 12ian34** [comment]
This has caused me problems too - I think along with extending the disappear delay, we could also consider extending the distance you need to move off the button for the hover menu to disappear. I've noticed this in other web apps and find it useful and more accessible.

**Comment by rephus** [comment]
We have recently updated the side bar, so this problem has been fixed in a different way (it persist until you click away) . Should we close this then ? 

[Screencast from 12-09-22 12:18:26.webm](https://user-images.githubusercontent.com/1983672/189630467-f6645278-d594-41cc-be5e-b9cec5455534.webm)

**Comment by ZeRego** [comment]
@rephus only persists if the field is selected. 
If the field is not selected and the mouse stops hovering the field element the options button/menu is hidden since we stop rendering it. 

We could change `packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/FieldButtons.tsx` to track the open state of the menu and change the line 168 to show the button/menu if the menu is open.
