### ISSUE TITLE
Table chart with extended pivot features or a dedicated pivot chart

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#3114]
The new pivot feature in the table chart is fantastic. However, it only solves a limited amount of use cases where pivoted data is needed.

I propose the following features in the table chart or as a dedicated pivot chart.

- Multi-level pivot by
- Collapsable groups
- Unlimited columns

https://www.loom.com/share/80cf373216824d3bb4255981ccd70052

[Pivot.xlsx](https://github.com/lightdash/lightdash/files/9460229/Pivot.xlsx)

**Comment by TuringLovesDeathMetal** [comment]
^I've broken this out into a couple of issues you can see above. 

but man oh man, the more and more I think about table visualizations, the more and more I think about this issue I added eons ago: https://github.com/lightdash/lightdash/issues/451

It feels like having the ability to "explore this data as a table" would be super powerful. 

I imagine you'd have the option to `open in SQL runner` in the SQL toggle, then `open as an explorer Table` or something in the `results` toggle which would open out this excel-like window where you could make some wild sheets

I guess the obvious next step would be: "I want to build a chart from some of the data I have in my explorer Table"

^I feel like this is where it might get a bit more complicated...

**Comment by Martin-Carlsson** [comment]
@TuringLovesDeathMetal 

I 100% agree on the power of Excel like features. People need and want to be able to do their own data manipulation.

One of the first things I was asked when I started talking about Lightdash was, does it allow to export data to Excel 😄

**Comment by TuringLovesDeathMetal** [comment]
^+1 to this!

I'm really hesitant on actually building Excel in Lightdash - because it kind of goes against the whole vision of "keeping all of your business logic in one place" and "having a semantic-layer approach to your BI" (basically, a single source of truth for metric + dimension definitions)

_**but**_ I think having a really good integration with Google Sheets or Excel would be amazing. 

Obviously Excel would need to be more import/export kind of vibes, but Google sheets could actually be a live connection with data that updated as the table updated. (so you could use a Lightdash connection in a sheet, then build stuff in another sheet using that data in the same workbook)

🔮 dreamy

**Comment by Martin-Carlsson** [comment]
> but I think having a really good integration with Google Sheets or Excel would be amazing.

^+1 to this!

Today, it is insanely difficult to data in to Excel/Google Sheet

**Comment by TuringLovesDeathMetal** [comment]
^ totally. Okay, opened an issue here: https://github.com/lightdash/lightdash/issues/3145

Would _**love**_ to hear more about "it is insanely difficult to data into Excel/Google sheets". What about it is really hard to do right now? 

Is it the getting data into Excel/Sheets from your BI? or is it getting it into your BI tool from Excel/Sheets?

**Comment by TuringLovesDeathMetal** [comment]
Closing this in favour of the issues I've opened + linked above!
