### ISSUE TITLE
Preview a subset of models on the CLI

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3135]
### Description

In the Lightdash UI you can filter the sidebar to show a subset of tables from dbt.

With the CLI you can also compile just a subset of tables with `lightdash preview -s tag:my-tag` for example. However in the preview environment it shows **all** the dbt models but has a warning triangle for anything that wasn't compiled saying

```text 
Model has not been compiled by dbt
```

It would be better the experience matched production. When I do `lightdash preview -s tag:my-tag` only models tagged with `my-tag` should show in the UI.

**EDIT**

This is also a problem with `lightdash deploy -s my-models` - we compile all models https://github.com/lightdash/lightdash/issues/3877

**Comment by TuringLovesDeathMetal** [comment]
This is kind of related to this issue? https://github.com/lightdash/lightdash/issues/2552

**Comment by owlas** [comment]
AH yeah. Would this be a solution to your problem? So if you could say "only build and preview models tagged with X, ignore any other models (whether they have errors or not)"

**Comment by TuringLovesDeathMetal** [comment]
kind of, but not really.

My use case is if I just run `lightdash preview`, I don't want to have to think about which models to preview vs. not. 

Then when I open the preview, if I see that one of the models I want isn't available, i can go back to dbt and run it, then re-preview. 

Right now, this doesn't work. Because if I do `lightdash preview` it will _**only**_ run if I have _**all**_ of my models available to be queried (it doesn't show these `warning` symbols like it does in the app if a model is broken/non existant)

This could solve it - by forcing me to know which models I want to test/preview before I do `lightdash preview` and having to list them all out. 

But, if I'm doing a big refactor and I've touched like 10 models that aren't really related to each other (except by one field in them), then trying to figure out which models they are and listing them in `lightdash preview -s` is a bit of a pain in the butt
