### ISSUE TITLE
Update spacing around titles on dashboard markdown tiles. 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3174]
<img width="512" alt="Screenshot 2022-09-06 at 16 20 42" src="https://user-images.githubusercontent.com/12776522/188673321-1bfa57f7-d62f-457c-b43e-ed71b3aca406.png">

There's too much space above! This affects markdown tiles where the user has left the `title` blank.

**Comment by PriPatel** [comment]
<img width="313" alt="Screenshot 2022-09-06 at 17 34 26" src="https://user-images.githubusercontent.com/12776522/188688710-36aacf34-88b7-4960-afa7-2b2b83ec0769.png">

Woops - its not a title, its a heading type

**Comment by rephus** [comment]
@PriPatel that empty space is happening because you didn't set a title. So the title is empty , leaving a white space at the top. 

![image](https://user-images.githubusercontent.com/1983672/206165641-d48cd0f9-a53e-4232-a95e-4d53f02d6159.png)
![image](https://user-images.githubusercontent.com/1983672/206165777-d5aef9f4-626f-48d4-909f-4c4476595f7b.png)

---

![image](https://user-images.githubusercontent.com/1983672/206165870-96a97d59-9bee-43db-aca9-47b986bf2434.png)
![image](https://user-images.githubusercontent.com/1983672/206165895-0ad5c2ce-a8a1-43d1-8414-39edaca11b79.png)



What do you suggest we do in this case ?

**Comment by PriPatel** [comment]
Are we easily able to remove the 'title' (white space)  bit **if** they have left it blank?

**Comment by rephus** [comment]
> If the buttons only appeared on hover, overlaying the title,

Yes !

**Comment by yasmin-e** [comment]
Investigated: Action menu is not overlayed on tile, so removing height when no title is given on `TileBase > HeaderContainer` makes the action menu unclickable
