### ISSUE TITLE
There is a space where you can see the users in your org

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#319]
In the `settings` dialog box, there should be a section underneath titled `Users` and then a list of email addresses of all of the users in the org. 

![image](https://user-images.githubusercontent.com/31848148/128527088-3c4c8ac4-1f5d-467f-9481-cd4fd495f42e.png)

## Tasks

- [ ] Backend `GET /users`
- [ ] Frontend UI for viewing all users .

**Comment by TuringLovesDeathMetal** [comment]
See this Sketch design: https://www.sketch.com/s/25c0de0d-219c-4d69-adfc-cf6def49044a

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal @owlas 
Thoughts on adding a `User management` tab instead of adding this table inside the organization tab ? 
The UX is going to be confusing since we will soon have actions in the users table and the `update` button at the bottom which updates the field which is at the top of the section.

The invite button would also be moved to this new tab. ( I would wait for that PR to be merged and change in this PR )

**Comment by TuringLovesDeathMetal** [comment]
@ZeRego ya, that sounds like a really great idea :) 

We were also talking about potentially changing the `settings` modal into a page...it feels like it's getting a bit big to be a modal. 
But not sure how you feel about that? or like what the "typical design principles" are for modal vs. page (is it totally chill to have this much content in a modal?)
