### ISSUE TITLE
I want to update an existing space and make it restricted/shared

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3202]
### User Acceptance Criteria
- [x] New spaces are created as `restricted` by default (only the person who created the space has access to it)
- [x] Once I'm in a space, I can adjust the access to that space (using the 'share' button)
- [x] I can switch a space between "full access" vs. "no access" 
  - [x] Switching between these just switches between their defaults (e.g. if I have a restricted space where I've also invited Priyanka, then I switch it to "shared", then I switch it back to "restricted", it would restrict the access to just me, it wouldn't keep the old configurations and add Priyanka too)
- [x] You're either given access to a space, or you aren't. There's no option to add someone as an editor vs. viewer when you're inviting an individual.
- [x] Everyone inherits the permissions that they have at a project level. There's no way to change these permissions in the spaces modal. 
- [x] if a space is restricted, I can only add individuals to the space (for now). I can't add groups of individuals (e.g. editors).
- [x] I can remove someone I've added to a restricted space

**Frontend stuff**
[User flow 
](https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=7715%3A95230&scaling=scale-down-width&page-id=7652%3A93147&starting-point-node-id=7652%3A93207)
[Components](https://www.figma.com/file/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=7652%3A93147)

**Comment by rephus** [comment]
> New spaces are created as restricted by default (only the person who created the space has access to it)
Even for other admins/edtiors ?

**Comment by ZeRego** [comment]
> Once I'm in a space, I can adjust the access to that space (using the 'share' button)

Can anyone in the space change between "full access" vs. "no access"

**Comment by TuringLovesDeathMetal** [comment]
> Even for other admins/edtiors ?

Yes

> Can anyone in the space change between "full access" vs. "no access" ?

Anyone with `edit` access to the space (so anyone who has edit or admin access to the project **_and_** who's been added to the space)

> Can anyone remove other users ?

Same as above - anyone with `edit` access to the space (so anyone who has edit or admin access to the project **_and_** who's been added to the space)

> Will the user be able to give the "space owner" role to another user?

No, there is no "space owner", only "space creator" (for now). I imagine later, we might introduce an idea of "space owner" and this could be assigned to different users. But for now, there is no special role for a space owner.

**Comment by owlas** [comment]
Suggestion for the backend to support this flow: adding access control lists to spaces. 

### Implement an Access Control List (ACL)

Currently we used Role Based Access Control (RBAC) to control access. Users have a role at the organization level and potentially a role for each project.

When we build an access profile for the user (a `MemberAbility`) we get their role for the organization and each project. This happens on every request, even if we we don't perform an action on project B, we'll build a profile with a role for project B. This would mean building a huge amount of roles if we continue with this approach for spaces and dashboards/charts.

We should move to ACL, where instead of attaching all possible access to the user's `MemberAbility`, we attach a list of authorised users to the Space/Chart/Dashboard.

I know this issue is only for private vs. shared. But here I include both private and having a separate ACL.

In this case the database would have a mapping table containing spaces and users:

```mermaid
erDiagram

user ||--|{ space_share : is
space ||--|{ space_share : is
space {
string space_uuid
boolean is_private
string shared_with
}
space_share {
  string space_uuid
  string user_uuid
  boolean is_private
}
user {
  string user_uuid
}
```

The `Space` can then contain the list of users with access (for now we assume this list is available to all users with view access on the space):

A space object would look like this:

```apib
# Spaces API

## space [/spaces/{spaceUuid}]

### Get [GET]
+ response 200 (application/json)

{
  "organizationUuid": "999b43d0-fc0d-4199-8a79-25b471c880bf",
  "uuid": "810b43d0-fc0d-4199-8a79-25b471c880bf",
  "name": "Shared space",
  "queries": [],
  "projectUuid": "770b43d0-fc0d-4199-8a79-25b471c880bf",
  "dashboards": [],
  "isPrivate": true,
  "access": [
    { userUuid: "...", ...},
    { userUuid: "...", ...},
  ],
}
```

The ability builder can use the space definition to check permissions. We can put this in the logic for the project viewer role by updating the conditions (see guide: https://casl.js.org/v5/en/guide/conditions-in-depth)

**Project viewers**

```typescript
# Conditions for a project viewer (or above) viewing a shared space
        can('view', 'Space', {
            projectUuid: member.projectUuid,
            isPrivate: false
        });

# Conditions for a project owner 
        can('view', 'Space', {
            projectUuid: member.projectUuid,
            isPrivate: true
            createdBy: member.userUuid,
        });
```

**Comment by rephus** [comment]
What does `is_private` mean on space_share relationship ? 
![image](https://user-images.githubusercontent.com/1983672/200769074-f506f94b-9323-4be3-a111-f58c505ad35f.png)

And also, don't we need to include a `role` here for users on spaces ?

**Comment by owlas** [comment]
Whoops that was a mistake. The `is_private` should live on the space table 🤦 

In the spec permissions are inherited from their project role so we don't need the `access` type on the `space_share` table. Although in future we'll want to do that. So if it's easier to add now rather than refactor, you could add an `access` to `space_share` and the space would return an access list like:

```
{
  "uuid": "810b43d0-fc0d-4199-8a79-25b471c880bf",
  "name": "Shared space",
  ...
  "isPrivate": true,
  "access": [
    { userUuid: "...", "access": "view"},
    { userUuid: "...", "access": "edit"}
    { userUuid: "..." },
  ],
}
```

`access` could be optional meaning that it inherits from the project? Or maybe that's a bit confusing. 

Simplest would be to not have any access on the `space_share` and inherit project perms

**Comment by owlas** [comment]
One more question @TuringLovesDeathMetal is there a chance we'll later have:

* Anyone in the org can view this space
* Anyone in the org can edit this space
* Nobody can view this space

^ in this case we should replace `is_private` with a flag like `org_can_edit` and `org_can_view` - what do you think?

**Comment by TuringLovesDeathMetal** [comment]
^Yes, I think so!

This feels like a really common pattern in a lot of tools and I can imagine people requesting this later on. We're not building it now because we couldn't agree on "can you _**increase**_ someone's permissions" (e.g. I'm a project viewer, but you make me a space editor). So we tried to reduce the scope and just use "full access" vs. "restricted"

**Comment by rephus** [comment]
I implemented the backend, we're still missing the frontend
