### ISSUE TITLE
Create a GitHub action for `lightdash preview` when a PR is created/updated/deleted

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3223]
### Description

when the PR opens, the github action creates a preview project using the code in the branch
when the PR updates, the github action updates the preview project ( deploy command )
when the PR closes, the github action deletes the preview project

- [ ] add docs on how to do set this up!
- [ ] add these docs to the app.

**Comment by rephus** [comment]
For this I'm picturing the following:

2 new  CLI commands: 
- start-preview : that will create a new preview with a given name (not random), we'll use the `branch name` of the PR . This command will not wait for a key to exit. 
If a preview env already exist, it will update it (just deploy) 
- stop-preview : This will `delete` the preview environment previously created (if exists) 

2 new GITHUB actions: 

```
on:
  pull_request:
    types: [opened, edited]
```
Calls start-preview: Create if it doesn't exist or update the environment if it exists. 
It is possible  that the first `preview` command fails (on opened) that's why it is better to make sure it exists, so we can create it from scratch on edit as well. 

```
on:
  pull_request:
    types: [close]
```

calls stop-preview : pretty straightforward, doesn't require dbt dependency.
