### ISSUE TITLE
[Close at end of milestone] You should be able to define `custom dimensions` in the UI

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3233]
### Description

I want to be able to create dimensions in the UI for things like bucketing groups. I don't want to have to do this in dbt because I might not know the groups I want to bucket in, or I might be bucketing things for a one-off analysis (e.g. comparing groups of users that I've defined using some product usage dimensions). 

this would be like table calculations or custom metrics (but more like table calculations...because you'd be able to write custom SQL). 

It would return a dimension type. That means users would be able to group by this field. 

E.g. I could create a dimension called `age group`. I'd define it like this:

```
CASE 
WHEN age > 20 THEN '20+'
WHEN age <= 20 THEN 'under 20'
```

This would return a field that I could use in my results table. It would act like a dimension (i.e. I could use it to group in charts). 

^This would fix #2699

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel do you have any suggestions of where this might live? 🤔 

These dimensions would be "based" off of other dimensions most of hte time (e.g. `age group` is just grouping `age` into buckets). But, sometimes they would use multiple dimensions in their definition (e.g. `age group type` = grouping by `age` and `cloud` vs. `self-hosted` into buckets) - so this would be more like table calculations.

^This might be an opportunity for us to think a bit about table calculations vs. custom metrics! (and how they're actually just the same thing 😅 )

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal 
Yes! So instead of custom metrics in the sidebar, we have a Calculations section. From here you can add table calcs, see your custom metrics and the grouped dimensions? Maybe calculations is the wrong word.

If we do this, I suggest that metrics, dimensions and calculations are collapsible somehow!

**Comment by ZeRego** [comment]
> (since table calculations would just be the same as custom metrics? 🤔 )

@TuringLovesDeathMetal Do you mean stop having table calculations or just group them with custom metrics ?
 
They look the same but they are different since metrics are defined in the first query and table calculations on the second query.

Example SQL
```
WITH metrics AS (
SELECT
  "dbt_orders".partner_name AS "dbt_orders_partner_name",
  AVG("dbt_orders".basket_total) AS "dbt_orders_average_of_basket_total"
FROM "thyme"."thyme"."dbt_orders" AS "dbt_orders"


GROUP BY 1
)
SELECT
  *,
  1 AS "tablecalc"
FROM metrics


LIMIT 500
```

**Comment by TuringLovesDeathMetal** [comment]
ah, okay - I meant stop having table calculations. 

I never actually understood why they were different to custom metrics, but now I think I do. Is it true that:

- custom metrics can only reference dimensions
- table calculations can reference dimensions and metrics

**Comment by TuringLovesDeathMetal** [comment]
^If they're actually different, then we should keep both! So ignore my comment above about removing `table calculations` then @PriPatel - I'll just need to update the docs to explain this a bit better.

**Comment by yu-iskw** [comment]
I would like the feature too so that we extract values from the JSON string. BigQuery offers [some JSON functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions) to extract information from JSON arrays and objects. For instance, the `JSON_EXTRACT` function enables us to access nested information in a JSON string. 

```
SELECT
  JSON_EXTRACT(JSON '{"class":{"students":[{"id":5},{"id":12}]}}', '$.class')
  AS json_data;

/*-----------------------------------*
 | json_data                         |
 +-----------------------------------+
 | {"students":[{"id":5},{"id":12}]} |
 *-----------------------------------*/
```

We tend to put some information to a JSON object in event logs of our services so that we flexibly persist some mislenious information without schema changes. So, data analysts have to extract nested information in a JSON string. 

Aside from that, we tend to analyze audit logs of Google Cloud sinked from Cloud Logging to BigQuery. As the sinked tables of audit logs contain JSON strings, we have to extract nested values with the JSON functions in BigQuery.

https://cloud.google.com/bigquery/docs/reference/auditlogs#example_most_popular_datasets
```sql
 #standardSQL
  SELECT
    REGEXP_EXTRACT(protopayload_auditlog.resourceName, '^projects/[^/]+/datasets/([^/]+)/tables') AS datasetRef,
    COUNT(DISTINCT REGEXP_EXTRACT(protopayload_auditlog.resourceName, '^projects/[^/]+/datasets/[^/]+/tables/(.*)$')) AS active_tables,
    COUNTIF(JSON_QUERY(protopayload_auditlog.metadataJson, "$.tableDataRead") IS NOT NULL) AS dataReadEvents,
    COUNTIF(JSON_QUERY(protopayload_auditlog.metadataJson, "$.tableDataChange") IS NOT NULL) AS dataChangeEvents
  FROM `my-project-id.auditlog_dataset.cloudaudit_googleapis_com_data_access_*`
  WHERE
    JSON_QUERY(protopayload_auditlog.metadataJson, "$.tableDataRead") IS NOT NULL
    OR JSON_QUERY(protopayload_auditlog.metadataJson, "$.tableDataChange") IS NOT NULL
  GROUP BY datasetRef
  ORDER BY datasetRef
```

So, if we can define custom dimensions in the UI, we can apply any expressions including functions to a dimension. That might be similar to the table calculation. 

In reality, we can apply any function to a dimension using the table calculation. Take the  orders table of the Jaffle shop project, for instance. The orders table contains the `coupon_amount` column. If we want to calculate the total numbers of order by whether or not using coupon. The expression can be `IF(${orders.coupon_amount} > 0, 1, 0)`. The resulting table in the UI is like below. 

![image](https://github.com/lightdash/lightdash/assets/1523515/5072c414-eca2-4466-9a2d-4a286054827b)

According to the genrated query, the table calculation is applyied to the aggregated data. As we can't aggregate resulting data by the table calculation, we can't calculated the total numbers of order by whether or not using coupon as far as I know. 
```sql
WITH metrics AS (
SELECT
  `orders`.coupon_amount AS `orders_coupon_amount`,
  COUNT(DISTINCT `orders`.order_id) AS `orders_total_orders`
FROM `test-project`.`jaffle_shop`.`orders` AS `orders`


GROUP BY 1
)
SELECT
  *,
  IF(`orders_coupon_amount` > 0, 1, 0) AS `use_coupon`
FROM metrics

ORDER BY `orders_total_orders` DESC
LIMIT 500
```

I tried to remove the referenced dimension of `coupon_amount`. It got the error.
```
coupon_amount
```
![image](https://github.com/lightdash/lightdash/assets/1523515/28eca593-cf5b-479a-b2fc-6924f164bb8f)


The our ultimate goal is to deal with nested information in a JSON string without creating a dbt model specialized for that purpose and withtout defining Lightdash dimensions in schema YAML. It would be great if we can apply any function to a dimension in the UI and aggregate data by the custom dimension.

**Comment by owlas** [comment]
Here's the most common requests for custom dimensions, I think we need to split these out into their own tickets:

- Binning a numerical value into categories
- Extracting JSON fields
- Arbitrary sql (for the power users)

**Comment by IrakliJani** [comment]
+1 customer asking for this
