### ISSUE TITLE
I created Bigquery a project on CLI without Location

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#3355]
### Description

I am able to create a project on the CLI, but I don't have location set on my profiles. So it created this project, but failed afterwards. 

Not sure if we need to ask for a location , or we can detect it, or we can connect on lightdash use it without location.

### To Reproduce

Have profiles.yml to look like this: 

![image](https://user-images.githubusercontent.com/1983672/193276036-7a09713c-4761-4c28-9770-86525205f473.png)

Create project on CLI 

![image](https://user-images.githubusercontent.com/1983672/193276068-a0447791-9eeb-4fe6-a1e7-5d4b912e30e6.png)

You get an error on the CLI, and this settings

![image](https://user-images.githubusercontent.com/1983672/193276153-57999e83-826b-471d-b13b-e76f73feed9b.png)

### App Version

- v0.268.0

**Comment by TuringLovesDeathMetal** [comment]
@rephus nice catch. I think we could do something like you suggested:

1. Look to see if they have `location` specified in their profiles.yml. If yes, use that
2. If no location is specified, then use the location based on their cloud instance location (for EU1.lightdash.cloud, use `EU`, for app.lightdash.cloud, use `US`)

^Out of curiosity, what happens if we get #2 wrong? Do we get the same error message as you get if you have no location defined? 

If we get an error message, then I'd suggest a 3rd action: 
3. If 1 & 2 don't work, then get the user to input their data location on the command line. Something like: `Enter your BigQuery dataset location then hit 'enter' (e.g. EU, US):`

**Comment by rephus** [comment]
> what happens if we get https://github.com/lightdash/lightdash/pull/2 wrong?

UNless you insert an invalid location , it seems to work fine... 

![Screenshot from 2022-10-03 16-42-31](https://user-images.githubusercontent.com/1983672/193606311-d4989bd1-d12b-412f-bf06-777968f0f5f8.png)


![Screenshot from 2022-10-03 16-43-34](https://user-images.githubusercontent.com/1983672/193606300-50c6511b-b86b-426a-9866-300f2a619832.png)
