### ISSUE TITLE
Add chart type to search results

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3391]
### Description

When I'm searching for charts to add to a dashboard, sometimes I don't know which chart name I'm looking for specifically, but I know the chart type. 

Adding the chart type to the search results could help me narrow down which option I'm looking for (the next step would be to add thumbnails...but chart types can actually be enough for some searches!)

**Comment by owlas** [comment]
Unlocked by #4196 and #4184

**Comment by PriPatel** [comment]
@yasmin-e I've assigned you to this one as you've just updated the icons! 
Rather than chart here, we need to show the actual chart type, much like we do on the homepage.
<img width="133" alt="Screenshot 2023-02-28 at 17 23 00" src="https://user-images.githubusercontent.com/12776522/221928881-2547e2ac-1874-4e1b-b32e-cfa4a5769298.png">

**Comment by TuringLovesDeathMetal** [comment]
This has been completed (there are icons in the search bar for each chart type)
