### ISSUE TITLE
axis labels are getting cropped in charts

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3473]
### Description

<img width="727" alt="image" src="https://user-images.githubusercontent.com/31848148/195176341-94e27cb2-1090-4963-95af-246d8ddb0d37.png">

If you have right-axis labels, they get cropped in a chart if it's too small. 

Expected behaviour: the chart should shrink so that the label still fits in the tile

**Comment by rephus** [comment]
I tried manually a combination of `overflow:visible` and `yAxis > nameTextStyle > padding ` properties to "fix" this. However, there are a couple of issues with this: 

- Some of the `overflow` properties can't be set in our code, because it happens inside the `echarts-for-react` component. I'm not sure if there is a way to fix this.
- The padding we need to set will depend on the label gap that we calculate dinamically based on the yAxis labels ... so it is hard and unreliable. 

@owlas suggested adding manually a `margin` on the chart for these cases. I tested it and that works. 

![image](https://user-images.githubusercontent.com/1983672/195331816-7feecefc-9709-49ec-b71d-b342e71c0cd0.png)
![Screenshot from 2022-10-12 13-30-21](https://user-images.githubusercontent.com/1983672/195331885-227f3d1c-5637-417d-871a-68ddd0d045d8.png)

![image](https://user-images.githubusercontent.com/1983672/195331685-57c149d1-32e1-4ecf-accb-5659c93ff135.png)

@TuringLovesDeathMetal what do you think ?

**Comment by TuringLovesDeathMetal** [comment]
right, I always forget that we have this margin padding thing 🙃 

Just to be clear, are you saying that the solution is to let users fix it themselves using the margin padding?

**Comment by rephus** [comment]
> Just to be clear, are you saying that the solution is to let users fix it themselves using the margin padding?

For now, yes, because an automatic solution in code is currently not possible.

**Comment by TuringLovesDeathMetal** [comment]
cool, sounds good!

Maybe I'll open a docs ticket and write some more info in there that we can point people to 👀

**Comment by rephus** [comment]
@TuringLovesDeathMetal should we close this then ?

**Comment by TuringLovesDeathMetal** [comment]
yep!
