### ISSUE TITLE
If you've selected a date column on the x-axis and the date values in your table aren't gapless, we should fill in the gaps

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#357]
I'm not actually sure whether or not we should do this...but I thought I'd stick it in so we could chat about it. 

Basically, if I have a table of data where the x-axis is built from a date dimension, but the dates in my table aren't gapless, then it produces a deceiving chart:

![image](https://user-images.githubusercontent.com/31848148/130249153-2eca0944-8454-4c78-917e-2c3d5c428e10.png)

It gives you the values that you have in the table (unsurprisingly), but what this means is you have a time series plot with a bunch of holes in it that are "invisible". 
I feel like if you have a date column, you want the x-axis to be a line of gapless dates: so you can see where there are NULL values and then you can see where there are actual values. 

One way of potentially doing this is by plotting the full date values, then anything that's empty is set to `null`. Then, in the chart options, you can pick `set null values to...` so that you can have 0 values instead of the `null` on your plot.

**Comment by ZeRego** [comment]
Was looking at the limitations of #458 and was thinking about how this feature should be implemented, it's limitations and if we should have this at the query/results level instead of the chart.

Implementation/limitation when doing in the chart:

1. date column has to be sorted
   - I don't think there is a way around this 
   - would we have this feature only available if the column is sorted ?
2. what would be the default values for the gap dates ? 
   - would we allow the user to define the value for each y axis ? 
   - how would we define dynamic default values ? Example when doing a running total ( https://youtu.be/aaCq2Tz-irU?t=242 )

 
Would it be possible for a SQL query to populate the time gaps ? 
If yes, the user would have total control over it and would be easier for our app to consume it.

**Comment by silentninja** [comment]
> Would it be possible for a SQL query to populate the time gaps ?

While it would be possible to use SQL, it would quite be limiting. I would love to have it in SQL if possible.

Limitations I can think of are:

1. Having to rerun the query just to switch the visualization(I usually fill gaps when looking at line chart and remove it when using bar chart)
2. Empty rows would also be part of the table
3. I would prefer to change the default value based on the context
4.  I would prefer to change the default value based on the scale(when looking at days it would be minutes if weeks would be days)

**Comment by TuringLovesDeathMetal** [comment]
This issue was closed in #458
