### ISSUE TITLE
The 'chart' panel should take up most of the screen height if it is the only panel that is open

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#3607]
**Problems**
- Once you're done with the results panel, it is likely that you will close it to then focus on the chart panel (to examine it, configure it etc.). Some charts end up look kinda cramped and messy because of the fixed height. It is also not ideal to have to scroll table charts especially when there is pivoted/grouped data. 
- You should still be able to open other panels and compare the results and charts tab - we are only talking about cases where the chart panel is the **_only one_** that is open. 

**Questions**
- Should this apply to the results panel as well? It would mean less scrolling.
- Should this affect view mode as well?
- Maybe this needs a POC and some fiddling around with to start off with!

**Comment by TuringLovesDeathMetal** [comment]
> Should this apply to the results panel as well? It would mean less scrolling.

Yes!

> Should this affect view mode as well?

Yes!

**Comment by IrakliJani** [comment]
**charts look good because they take up the most space.**

![image](https://user-images.githubusercontent.com/962095/199485052-ffe7619c-c9e9-4f74-80ba-fae70c2a0b4f.png)

**but not results table**

![image](https://user-images.githubusercontent.com/962095/199485095-0838636b-8334-4366-a89b-cf16de9a791b.png)

**unless its a scrolling results view.**

![image](https://user-images.githubusercontent.com/962095/199485135-5b48ab77-e0b9-4822-acba-3120903a343b.png)


cc: @PriPatel @TuringLovesDeathMetal

**Comment by TuringLovesDeathMetal** [comment]
This is great! no worries about the results table - if it's really bothering you, then we can make the results `scroll` by default, then it kinda solves it?
