### ISSUE TITLE
I can't see charts I have no access to when I'm adding tiles to a dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3643]
### Description

When I'm creating a new dashboard and adding tiles, I shouldn't be able to see saved charts that I don't have access to (e.g. ones in a restricted space I don't have access to).

I should only see a list of charts I have access to in the add tiles list. All other charts should be removed.

**Comment by rephus** [comment]
We don't need to do anything, this automagically works because we list those charts from the /space endpoint, which means that we only show charts from spaces the user have access to. 

![Screenshot from 2022-11-17 09-45-42](https://user-images.githubusercontent.com/1983672/202399450-c9784eda-6d06-4616-9483-a980b669a0ba.png)

**Comment by rephus** [comment]
@PriPatel @owlas could you confirm we can close this ?

**Comment by PriPatel** [comment]
Yep, sounds good

**Comment by rephus** [comment]
![simpsons-leonardo-nimoy](https://user-images.githubusercontent.com/1983672/202405203-b240d2a4-6553-43a9-a388-8054f435a351.gif)
