### ISSUE TITLE
relevant dbt test failures are shown to you when you're looking at a chart/building a chart in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#366]
When dbt compiles, we get information about test failures from the metadata. 

If a test fails for a field/model that you use in Lightdash, we should tell you about it. 

E.g. I'm building a chart, using `count_unique_user_id` which is built from `user_id` . 

The field `user_id` has a test for `unique` values in the column. 

This test fails. 

I'm alerted in Lightdash that the `count_unique_user_id` field might have some problems because the `user_id` test has failed in the compile.

**Comment by yu-iskw** [comment]
@TuringLovesDeathMetal This is a great idea. Besides, one of the common cases is less-fresh data of a table, because any upstream dbt Model is failed. As the native trait of `dbt build`, downsstream models of a failed one aren't executed. Even though tests of a downstream model of a failed one aren't failed, the data isn't fresh. Just showing the freshness of a table on the Lightdash UI might be useful.
