### ISSUE TITLE
Attribute Based Access Control

### ISSUE THREAD

**Issue by mike-weinberg** [lightdash/lightdash#3793]
### Description
What is ABAC? NIST wrote a book on it in 2018. The US government and Okta both concluded it is usually a superior security model at scale. ABAC is when you assign attributes to assets, to entities, and to environments and define policies that relate those attributes together using logic that can compare or even compute over the values of those attributes.

EG: a policy might be “CEO office door access” and it might relate the time of day, the entity’s job function, and the entity’s employment start and end dates. Only ABAC lets you define a policy like: the CEO’s office can be accessed by the CEO at any time, by facilities staff during daylight hours including weekends, and by executive assistants to the CEO on weekdays. 

In lightdash we might have ABAC look like:
- Assets/Data:  dimensions, measures, spaces, and in a limited sense, dimension values (the only attribute of a dimension value would be the value itself, but technically that is still an attribute to which a policy can be applied). 
- Entities: users
- Environments: time, region
- Asset attributes can be tags on assets, asset system metadata, or, if the asset is a dimension value, the actual value of the asset  

### What problem does this solve?

Today, IT and compliance departments are unable to collaboratively manage security policies on data assets. IT can comprehensively control entity attributes via IdPs but they are effectively disconnected completely from the data assets in use by those entities, and compliance teams are unable to collaborate because they are required to conform to the security architecture of the data products, which generally do not leverage ABAC. Therefore, today, data engineers are frequently responsible for defining and implementing security policies as a service to IT and compliance. This is not productive. 

ABAC would enable HR, compliance analysts, data engineers, and IT to collaborate using a common language, define attributes and policies collaboratively and minimize the involvement of data engineers in governance by delegating maintenance of entity attributes to IT+HR and by delegating maintenance of asset attributes to compliance analysts. compliance analysts could potentially even be trained to handle authorship of most policy definition, with only the most complex cases requiring help from engineers (eg policies that need to perform string parsing/regex or other similarly complex policy logic) 

This works best if entity attributes can optionally be inherited from an IdP while asset/data attributes can/must be inherited from DBT / DWH metadata. An attribute browser and policy engine would need to be implemented by lightdash no matter what. 

Note: resolving this would implicitly resolve #1243 and #1245

**Comment by owlas** [comment]
Great issue @mike-weinberg ! Under the hood, we're actually using ABAC for managing permissions. The central area for defining rules and attribute checking happens in this directory: https://github.com/lightdash/lightdash/tree/main/packages/common/src/authorization

We launched "roles" for the first version of permissions because it's a simple UX but ultimately it isn't flexible enough. So we built our roles on top of an ABAC implementation.

I think a full implementation would have the following features:
* Adding groups
* Adding custom user/group attributes
* Make custom attributes available in content / metrics / project configuration
* Make attributes available in queries (row-based security)
* Content-level permissions (we're just implementing this now)

Is there something I've missed? I think it would be great to make sure this is captured on a bunch of smaller feature requests
