### ISSUE TITLE
Increase RunQuery timeout to 300 seconds ( 5 minutes )

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#4047]
### Description

Error when a query takes too long

![Screen Shot 2022-12-21 at 5 13 05 PM](https://user-images.githubusercontent.com/9117144/210536679-800e1f0f-dd35-47b7-be28-87dbcd66136e.png)

Express might also have a default we need to override (2mins by default?) 

### Acceptance criteria

- [ ] Make sure we can run long queries up to 300 seconds (5 minutes).

**Comment by ZeRego** [comment]
The problem doesn't seem to be our express server.
I added a setTimeOut to force the express server to return only after 6 seconds and everything worked well.
![Screenshot 2023-01-04 at 10 48 23](https://user-images.githubusercontent.com/9117144/210542560-5cf71b99-bbad-49d0-a73e-8c87cb596413.png)

Is not a query that is so big that is timing out since `pg` library [doesn't have a timeout by default](https://node-postgres.com/apis/client) and when I forced a timeout value the error was different.
![Screenshot 2023-01-04 at 11 10 21](https://user-images.githubusercontent.com/9117144/210542957-1189701f-8566-4a46-894b-6188f8838ff6.png)

 

`connect TIMEDOUT` seems to be a specific Redshift [error when the SSL mode value is incorrect](https://github.com/brianc/node-postgres/issues/1555).
