### ISSUE TITLE
Stacked bar order and colours change when applying then removing a filter

### ISSUE THREAD

**Issue by Jake-Curtis** [lightdash/lightdash#4166]
### Description

Hoping this hasn't been flagged already elsewhere! When applying a new filter to a dashboard, then removing it, the original order of stacked bars and their colours changes randomly.

### To Reproduce

https://www.loom.com/share/581f3081396b40e08f1249050282f094
1. Open a dashboard with a stacked bar chart
2. Apply a new dashboard filter which changes the number of stacks of the bar that is shown
3. Remove that filter

### App Version
v0.350.3

**Comment by rephus** [comment]
The problem is that we store series config on `VisualizationContext` when we do filtering, so the series are overwritten when the filtering happens, so the color info is gone. 

The easiest way is to fix this is by forcing a component re-mount instead of a re-render. So charts are built using the `initialChartConfig` from savedChart and not the internal state.
