### ISSUE TITLE
Proposal to use query builder library for filters

### ISSUE THREAD

**Issue by silentninja** [lightdash/lightdash#424]
I came across few libraries([Awesome query builder](https://ukrbublik.github.io/react-awesome-query-builder/), [React query builder](https://react-querybuilder.github.io/react-querybuilder/)) that could help us move faster with filters. Wanted to know if they have been considered. 

We might have to write an adapter but could help us in the long run as a major portion of the work/maintenance can be offloaded.  Not sure of the policies regarding the library but it might be worth taking a look instead of reinventing.

**Comment by ZeRego** [comment]
Thanks for the tip!
I didn't know about these. I going to have a look at them today and see if/how we could use them.

**Comment by ZeRego** [comment]
Update: 
We had a look at `react-awesome-query-builder` first since it is more populated in npm. We created 2 feature requests in their repo:
https://github.com/ukrbublik/react-awesome-query-builder/issues/495
https://github.com/ukrbublik/react-awesome-query-builder/issues/494
POC branch: 
https://github.com/lightdash/lightdash/tree/refactor-filters-with-lib

Doing a deeper dive into `react-querybuilder` next week. But by quickly checking their docs, it seems we can override the sql formatter as we wish. https://github.com/react-querybuilder/react-querybuilder#querybuilder

**Comment by silentninja** [comment]
While you are at it, it would be better to look at the way filters are stored. Right now filters are being saved as json string. It would be better if they are stored as objects. As filters can be saved/named/queried in future.

I am thinking of something like:

```js
[{
uid: number,
parent: number | undefined,
// other fields
}]

//On the frontend
{
id: number,//Id the querybuilders emit, should be same as `uid` once saved on the backend
parent: number,
uid: number, 
// other fields
}
```

**Comment by silentninja** [comment]
I am thinking of using them to get the json object and ignore the sql formatters as I am not sure if our project needs might match theirs.
