### ISSUE TITLE
The number of views per dashboard is not being displayed on the homepage

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4323]
https://demo.lightdash.com/projects/2014e038-ff4b-4761-ae6f-fbf551e7b468/home
<img width="280" alt="Screenshot 2023-01-30 at 18 24 04" src="https://user-images.githubusercontent.com/12776522/215505260-0faacb90-34c5-4f1d-ab54-e3746e3cebef.png">

**Comment by IrakliJani** [comment]
attaching a video (btw I already fixed a bug with 0 views (it now shows "0 views" instead of "views")

but here are more bugs. viewing chart → +2 chart views
viewing dashboard → +1 chart view (which is correct!)
viewing a dashboard → +0 dashboard views

https://user-images.githubusercontent.com/962095/215548585-e5f756ea-6bfb-429b-9809-27bf9578cce6.mp4
