### ISSUE TITLE
incorrect behaviour when picking new start date within "is between" filter

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#4330]
### Description

incorrect behaviour when picking new start date within "is between" filter
### To Reproduce

1. go to explore
2. open filters
3. select some field with `date` type
4. select `is between` operator
5. pick a `start date` and `end date`
6. change start date to be from different month
7. 💥

https://user-images.githubusercontent.com/962095/215696103-cffa393a-ee11-42ab-9b12-1b7155dd7f6c.mp4

**Comment by rephus** [comment]
This is happening because the first date is supposed to be before the second date, in your video you picked a later date. It works fine if you change it to an earlier date. What do you think is should happen here ? do you think we should simply select a range , without caring which one goes first ? 

[Screencast from 01-02-23 10:47:00.webm](https://user-images.githubusercontent.com/1983672/216009265-d4fb4da2-aba6-47f4-b8c8-2575bb97cb21.webm)

**Comment by IrakliJani** [comment]
attaching additional videos

us:
https://user-images.githubusercontent.com/962095/216026992-ce0d1e10-f69f-4b1e-a8a0-551ab9c11f19.mp4

vs blueprint:
https://user-images.githubusercontent.com/962095/216027019-736a45b7-f6ca-4137-9404-b9ce63cabee3.mp4
