### ISSUE TITLE
Lightdash puts quotes around column names causing an `unexpected string literal` error in BigQuery connection

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#456]
We've added SQL compiling which puts quotes around column names. This breaks in BigQuery. 
![image](https://user-images.githubusercontent.com/31848148/134030177-cdc6e533-b7ab-44ec-837b-a43f359ccb42.png)

![image](https://user-images.githubusercontent.com/31848148/134030290-96f698d8-9428-44e5-b40c-dc5af5b1f39b.png)

**Comment by owlas** [comment]
Thanks @TuringLovesDeathMetal - in bigquery they should be backticks rather than double quotes. Not sure what's gone wrong here. 

Here is the quote character map for each of the adapter types:

https://github.com/lightdash/lightdash/blob/2d8789280feda006e92e5e68c049812f63186093/packages/backend/src/queryBuilder.ts#L206-L220

It defaults to double quotes, so I guess we aren't getting the adapter type correctly for the project  

@TuringLovesDeathMetal do you have access to the `manifest.json` file for the project?
