### ISSUE TITLE
I want filters to be more user-friendly in dashboards/saved charts for business users

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4604]
### Description

Our filters are pretty complicated and scary for folks who aren't used to thinking about logical expressions in SQL. 

Here are some of the points of feedback:

- [ ] the date filtering options are a lot to be presented with if you're not too used to date filtering (e.g. `in the last`, `on or before`, `on`, `on or after`). Can we make these less complicated? (e.g. relative vs. non-relative groups? Using more calendars for picking?)
- [ ] Sometimes I want to limit the options that people can filter on in dashboards. (there are a bunch of examples of this in this issue: https://github.com/lightdash/lightdash/issues/4173). Also, see Tableau's example here: https://help.tableau.com/current/pro/desktop/en-us/filtering.htm#set-options-for-filter-card-interaction-and-appearance
- [x] I want to set empty values in my filters so that people know which fields they can/should be filtering on (there's an open issue for this here: https://github.com/lightdash/lightdash/issues/3212) 
- [ ] I want more buttons/toggle type interfaces for filters in my dashboards

**Comment by TuringLovesDeathMetal** [comment]
cc: @PriPatel in case you have any more feedback to add here!

**Comment by PriPatel** [comment]
More specific feedback on date filtering here!  :
 https://github.com/lightdash/lightdash/issues/4240

**Comment by kandji-ross** [comment]
I left some more specifics on [4173](https://github.com/lightdash/lightdash/issues/4173), but in general, I feel like the key is differentiating between filters that are defined as part of the data model vs filters that are expected to be interacted with by end users. There may be some filters I don't _want_ end users to be able to touch (e.g. if I'm building a dashboard on churned customers, I don't want someone to be able to deselect "churned = true"), and there are others I really want to foreground and expect end users to interact with regularly (e.g. this dataset contains 17 different product categories, but users usually just want to see one or two at a time, and I want to make it easy for them to toggle back and forth quickly).

**Comment by ZeRego** [comment]
Request from the community to have dashboard filters that can't be removed but the value can be changed. 

> Dasha Zhytanska
In my case, I want to present information on the dashboard for specific user that you can choose in the filter. But if the filter was deleted (maybe accidentally), I need to see info in charts that you need to select user in filter. So I thought if I can’t add text to chart, maybe I can use permanent filter.

> Sasha
Pretty common use case indeed. We had those in older reporting tools.
Let's say we have a pretty powerful model with a lot of applications.
And there's a particular way to filter it's data to get some specific information out of it.
e.g. we have tracking events model, and some of those events are part of AB tests.
So in order to pull AB related metrics right one needs always use that filter to the model. Obviously end user won't necessary know that and might just kill the wtf filter on his dashboard. then all the data is mixed up.
I'd even go further with the feature. Would it be possible to 1 lock filter, and 2 hide from the end users.

> Sasha
Another common use case is for embedding reports. Yes, it's not part of Lightdash functionality. yet :grimacing:
so we want to embed some report that focuses on a particular campaign/product and etc. Filter has to be set and should not be removable as whole report/dashboard is built considering single campaign/product focus.

**Comment by ZeRego** [comment]
> Anna
I generally add is not null filter when want to leave opportunity for user to filter by proper column (then dashboard user changes is not null to needed value in order to filter). And also will be very helpful to have non-removable filters, generally I hardcode such filters inside charts, but having them on dashboard level will be more transparent for dashboard users understanding. I would even add an option to hardcode values user can't change. Good example is [always filter](https://cloud.google.com/looker/docs/reference/param-explore-always-filter) in looker (might be worth thinking whether this is something that should be added to yaml setup :thinkspin:

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as we have loads of issues that are related to this (and this is more like a feedback thread instead of an actual issue). 

https://github.com/lightdash/lightdash/issues/8882
https://github.com/lightdash/lightdash/issues/4363

**Comment by TuringLovesDeathMetal** [comment]
We've also shipped `any value` filters since this thread! (which resolves quite a few of the issues mentioned)
