### ISSUE TITLE
Show permissions and content summary when you hover over Space items

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#4620]
- [ ] Show more permissions info on hover
- [ ] Remove the dashboard/chart count from the Space component and show it in the same tooltip instead
<img width="393" alt="Screenshot 2023-03-03 at 14 20 38" src="https://user-images.githubusercontent.com/12776522/222743971-2678b8ca-5f94-4982-b624-c85af27b985f.png">

Icon | Title on component | Permission on hover
-- | -- | --
`lock` | Private | Only visible to you
`user` | Shared | Shared with XX users
`users` | Public | Everyone in this project has access
  |   |  
<img width="775" alt="Screenshot 2023-03-03 at 14 27 29" src="https://user-images.githubusercontent.com/12776522/222744921-67ccddf7-dca8-460c-8899-10eeebe7016f.png">

**Comment by Chrischuck** [comment]
@PriPatel after remove the dashboard/chart icons and putting them into a tooltip, the width of the card looks a little funky because they shrunk down. Is there guidance on how they should look after removal and for longer space names?

<img width="699" alt="Screenshot 2023-03-04 at 11 27 43 AM" src="https://user-images.githubusercontent.com/13311268/222920236-c06f2101-5fcd-445c-8f58-911986832a6c.png">


Also I don't think the current implementation has the necessary attributes to determine # of users and the difference between shared/public.

From what I saw, there were three states for a space:

`!isPrivate` -> Public space
`item.data.access.length > 1` -> Shared space (though this case would never be reached because the above state would execute first
`else` -> Private space

From what I could pick up, `item.data.access` is not a full list of users who have access to the space?

I __think__ the api might have to include a count of users w/ access to the space and maybe add an `accessType` enum: `PRIVATE`, `RESTRICTED`, `PUBLIC`?

**Comment by IrakliJani** [comment]
@Chrischuck I think you already resolved the first issue about spacing.

> Also I don't think the current implementation has the necessary attributes to determine # of users and the difference between shared/public.

also, your current implementation is accurate
