### ISSUE TITLE
Bad dates when exporting CSV with raw format

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4723]
### Description

CSV dates should always be correctly "formatted" 

### To Reproduce

Select date dimensions and export CSV with format 'raw' 

![Captura de ecrã 2023-03-08, às 10 21 59](https://user-images.githubusercontent.com/9117144/223687511-3e069b25-5fb7-46fb-9146-b9c7e1e93ff1.png)

### App Version

0.448.0

**Comment by jnfrati** [comment]
Hey @ZeRego! 
Wanted to tackle down this one, but I wanted to be sure I'm not missing anything.

In the case where a column is a date instead of returning `1485774000000`  the idea is to return `2017-01-30 11:00:00` no matter if the "raw" option is enabled or not right?

Also found out that the CsvService is where this might be happening, is there any other place where csv might be created?

Thanks!

**Comment by ZeRego** [comment]
Hi @jnfrati 👋 

Assigning the ticket to you :) Thanks for contributing 

The fix should be in `convertApiToCsv` -> `csvBody` loop. We need to change the date independently of the `onlyRaw` value`.

**Comment by jnfrati** [comment]
I think my latest PR #4771 should fix it! Can you take a look at it @ZeRego? Thanks!
