### ISSUE TITLE
Investigate the bottleneck in .csv export limitations

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4760]
### Description

Right now, we have 1Gb of RAM in the server. We shouldn't be getting memory errors with just a 20Mb file. 

Can we consistently replicate this on analytics? Is there a memory that's maybe causing this?

**Comment by rephus** [comment]
## Testing in analytics

I can consistently kill analytics server by requesting a 300k row csv file (1 column )  https://analytics.lightdash.cloud/share/Y_t_vDnbiZU9U7u_2SNPL

The reason is: 

```
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
```


Right now analytics has the following resources: 

```
    Limits:
      cpu:                475m
      ephemeral-storage:  1Gi
      memory:             725Mi
    Requests:
      cpu:                475m
      ephemeral-storage:  1Gi
      memory:             725Mi
```

I increased /livez and /health timeouts tot 60s to confirm this was not another `blocking request` 

## JS memory usage

I've been running this method to test the JS memorry with `process.memoryUsage();` usage while downloading CSVs...

```setInterval(() => console.log(process.memoryUsage()) , 1000)```

Last memory output: 
```
{
  rss: 41517056,
  heapTotal: 6696960,
  heapUsed: 5572248,
  external: 964903,
  arrayBuffers: 10469
}
```
