### ISSUE TITLE
Dashboard link sharing isn't applying the changes to filters from view-only mode

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4994]
### Description

Imagine I have a dashboard with a saved filter on it (e.g. date in the last 14 weeks). There are a few things that happen when I try to update the filters in view-mode:

1. If I add a filter in view mode, then click on the `share link` button, it doesn't include the filter from view-mode. (but it does get included if I copy-and-paste the link from the browser). 
2. If I change the saved filter in view mode, then click on the `share link` button **_**or**_** try to copy-paste the link from the browser, it doesn't keep the updates to the saved filter. 

https://www.loom.com/share/090f3789564b488badd1ec1edcb976fa

**Comment by rephus** [comment]
The share link on dashboard is not like the share link in explore , where it is storing the explore full URL on DB to minimize the shared URL

On dashboards, we simply copy the URL to the current dashboard, not even the Browser URL: 

    url={`${window.location.origin}/projects/${projectUuid}/dashboards/${dashboardUuid}/view`} (DashboardHeader)

There are 2 options here: 

1: SImply copy the current location.href to the dashboard, with the current content, this is a trivial change. This should not cause the same issues that we had on explore, because the URL are shorter on dashboards. 

2: Implement the same URL shortener from explore. The backend is compatible (even slack unfurling should work with these), most of the changes are frontend. This is a few hours job, but we will have nice shared URLs eg: `https://app.lightdash.cloud/share/y8VJw5THIviwL-2l7xb2y`

@TuringLovesDeathMetal what do you think ?

**Comment by TuringLovesDeathMetal** [comment]
@rephus I feel like the trivial change is good for now! (option 1)

If you share option 1 in Slack, will it still unfurl though? Or will that only work with option 2?

**Comment by rephus** [comment]
> @rephus I feel like the trivial change is good for now! (option 1)
> 
> If you share option 1 in Slack, will it still unfurl though? Or will that only work with option 2?

Right now, unfurling dashboards with any extra arguments does not work , it throws an error, I'll create a separate ticket to fix this 

http://localhost:3000/minimal/projects/3675b69e-8324-4110-bdca-059031aa8da3/dashboards/d823a06d-1159-4d53-979a-3f2eb0b26988?filters={}

![image](https://user-images.githubusercontent.com/1983672/231409799-8f86b05b-e3af-41d4-9c26-b3e29b715f2e.png)

Option 2 will not fix it anyway.
