### ISSUE TITLE
Analytics event for `metrics as rows`

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5304]
### Description

When a user runs a query with `metrics as rows`, we should add this to the `query_executed` event. 

Add this as a field `metrics_as_rows`  in `query_executed` which is either TRUE or FALSE

**Comment by owlas** [comment]
Just looked at this and our `query_executed` event happens when any time a query runs, which can be for underlying data or creating a csv and also for viewing a chart.

Would it be useful for this to be `true` if there is a chart with metrics as rows and `false` for any other case, even in the case a query is not executing for the purpose of creating a chart?

We could also have a new event specifically to do with running charts.
