### ISSUE TITLE
Investigate issues with joining organizations

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5307]
### Description

https://lightdash.slack.com/archives/C03MCQ08UKS/p1683024102319309

This could be a race condition on joining org

**Comment by NoraKeese** [comment]
Following Email adress is not able to sign up to lightdash marie.jensen@kontist.com.

The Email adress has been added via lightdash 
![image](https://user-images.githubusercontent.com/118756759/235665235-cd0ba22b-73b6-424a-97b9-32af47dc87b4.png)

She recieved the invite link and got here

**Comment by rephus** [comment]
From slack: 

It could be that we aren’t handling the error correctly from okta. So when folks login with Okta they see the error “User is not assigned to the client application” - that means that the okta user hasn’t been allowed to “login to lightdash with okta” in the okta admin panel.

But perhaps when that happens we’re still creating a user in Lightdash and this happens:

- User signs in with [me@lightdash.com](mailto:me@lightdash.com)
- See Lightdash error since Okta has not allowed [me@lightdash.com](mailto:me@lightdash.com) to login to Lightdash with okta SSO
- Lightdash creates a user anyway with [me@lightdash.com](mailto:me@lightdash.com)
[me@lightdash.com](mailto:me@lightdash.com) asks lightdash’s okta admins to enable login for Lightdash on their account
- User tries to register again but Lightdash shows “user already in use”

Could that be the problem?

I’m wondering if error handling is missing here: https://github.com/lightdash/lightdash/blob/679312d98b7dcf509d5471b52d96feb3beaa9b2c/packages/backend/src/controllers/authentication.ts#L207-L207

**Comment by rephus** [comment]
@owlas is it possible to debug okta locally ?

**Comment by TuringLovesDeathMetal** [comment]
No mention of this issue in nearly a year. Closing as not planned
