### ISSUE TITLE
MySQL Integration

### ISSUE THREAD

**Issue by Dkurupp** [lightdash/lightdash#5706]
### Description

Could you also integrate with MySQL?

### What problem does this solve?

Most of the solutions I have built over the last few years has been on MySQL. Hence the request

**Comment by uraurora** [comment]
same, and I thought mysql was one of popular database solutions above all, I'm also confused that dbt doesnot support mysql by default

**Comment by 12ian34** [comment]
Hi @Dkurupp @uraurora , 

We already have an issue for this in #3769 

Note that since adding support for [Trino](https://docs.lightdash.com/get-started/setup-lightdash/connect-project#Trino) recently, we can suport MySQL users if they use [Trino](https://trino.io/docs/current/connector/mysql.html) as a conduit.
