### ISSUE TITLE
Add context to saved charts list

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#573]
Unless you name your saved charts really clearly, it's hard to find exactly the chart you want.

Some context that would be useful:
- [ ] The chart type 
- [ ] A thumbnail of the chart?
- [ ] The metrics or dimensions on it

Then given a long list of saved charts, it's easier for me to find what I'm looking for.

<img width="1526" alt="Screenshot 2021-10-11 at 12 03 35" src="https://user-images.githubusercontent.com/11660098/136779996-32b28bfe-5c44-4a21-a0ed-0705c228bd48.png">

Looks like we only return names to the FE currently so we would need to update the backend for listing queries in a space: 

https://github.com/lightdash/lightdash/blob/1266cf1057e52931e980d48ab58160356a07e861/packages/common/src/index.ts#L859-L879

**Comment by owlas** [comment]
@PriPatel this was something we considered for navigating the list of saved charts. Since the words don't really help you find what you want.

**Comment by PriPatel** [comment]
Some ideas!

**Thumbnail** - This could work but I think the preview would have to be a certain size in order to make sense. It might end up looking like another dashboard and you would have to scroll loads to find what you want
**Chart type** - We could use icons from our blueprint library. Would this help though? I'm just thinking about instance - I don't think seeing type charts would help me as a data consumer.
**Author** - This can be automated and could help _some_ teams. Again, Im thinking about our instance where the charts are mainly made by one person. 
**Emojis** - This could be fun (and a bit silly) (see attached screenshot). When the user creates chart, as well as naming it, they could pick a relevant emoji! (sort of like what happens when you create a new Notion page)
**Dashboard** - Display which dashboard(s) the charts appear in? Could this immediately give you some context ? This only works for bigger teams with multiple dashboards. 
**Date created** - Automated. Add sort function so you can see the most recent? Sort by alphabetical order? 

To be honest, this depends on a lot. It feels like if you have 20+ saved charts, you're going to need some sort of filtering/sorting especially you're a team. Another thing we could do is encourage the users to name their charts clearly at the 'create' stage.



![Screenshot 2021-12-17 at 10 50 00](https://user-images.githubusercontent.com/12776522/146533482-63fce040-0e3a-4856-bbf9-d6eedde8dc33.png)
![Screenshot 2021-12-17 at 10 49 54](https://user-images.githubusercontent.com/12776522/146533484-e9262efb-1e6e-4704-87bd-98a25ed7593d.png)
![Screenshot 2021-12-17 at 10 49 57](https://user-images.githubusercontent.com/12776522/146533486-b8da198c-36c5-46da-bfbc-9d974ea3964e.png)

**Comment by TuringLovesDeathMetal** [comment]
@PriPatel @owlas 

@hamzahc1 and I were talking about this in our virtual desk chat and we were saying the most important things that are missing for us right now are:
1. **Who made it?** Situation where this came up: Hamzah copied one of my charts, and renamed it to something similar. But he couldn't figure out which one he'd made vs. I'd made just from the title. (#1311)
2. **When was it made?** Situation where this came up: the other day I realized I created the same saved chart twice, but couldn't figure out which one was the one I'd _**just**_ created. (#1310 )

^Assuming your charts had good titles, these would be the "lowest hanging fruit" in terms of important context. 

Later on, we can add more complicated things like "tags" or other filters.
