### ISSUE TITLE
Prevent browsers from populating warehouse credentials inputs

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#5900]
### Description

There are HTML attributes that indicate to the browser to not populate specific inputs, but browsers aren't required to comply.
More details:
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password

We should use these attributes even if it doesn't cover 100% of the browsers. We hope all browsers will eventually comply.

### To Reproduce

Steps:
1. have your lightdash user/password saved in Chrome password manager
2. Go to project settings
4. See user and password inputs populated

### App Version

0.611.0

**Comment by owlas** [comment]
I believe this behaviour is very useful depending on the browser implementation. This was raised because a user found that the form was autocompleted with their Lightdash username + password but this is not always the case. But in some cases the users actually do have their warehouse credentials in their password manager.

**Comment by wasifkareem** [comment]
Hi @ZeRego , Can I work on this issue??

**Comment by TuringLovesDeathMetal** [comment]
I'm closing this issue as not planned! THis hasn't been requested by other users since opened and is stale
