### ISSUE TITLE
Viewer user shouldn't see buttons that edit data

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6105]
### To Reproduce

Viewer can see the edit and options buttons. They should be hidden.

![Captura de ecrã 2023-06-30, às 10 34 41](https://github.com/lightdash/lightdash/assets/9117144/05f16ecf-5f68-4bc1-a27f-aa5bd84251cc)
![Captura de ecrã 2023-06-30, às 10 34 51](https://github.com/lightdash/lightdash/assets/9117144/02ce7152-d2a3-4f93-846f-f5b55a624f75)
![Captura de ecrã 2023-06-30, às 10 35 01](https://github.com/lightdash/lightdash/assets/9117144/a1d9ddb8-3ee8-4d90-ac45-5ed8eebf179e)

![Captura de ecrã 2023-06-30, às 10 36 06](https://github.com/lightdash/lightdash/assets/9117144/1c59ed42-f6fd-4401-bfdf-51cdcdc4a8cb)

![Captura de ecrã 2023-06-30, às 10 31 11](https://github.com/lightdash/lightdash/assets/9117144/2acf7943-be2d-4a48-a989-7474626f87bc)
### App Version

0.640.0

**Comment by rephus** [comment]
LT;DR : An `editor` on a project can also get edit access on a project he's only supposed to `view` . The problem is likely that we don’t pass the project uuid to the check

This should only be affecting some buttons on the frontend. 

## How to replicate: 

- as an admin, create a Project A and a project B 
- Invite a new user, with `view` permissions on the org
- Give this user `edit` permissions to project A
- :fire: Now this user will also have `edit` buttons on project B

## How we should fix this

 Instead of 
 
 ```
  <Can
                        I={'update'}
                        this={subject('Organization', {
                            organizationUuid: data?.organizationUuid,
                        })}
                    >
                    ```
                    
                    
                    We need to do add the `                    projectUuid` to the subject like this: 
                    
                     ```
  <Can
                        I={'update'}
                        this={subject('Organization', {
                            organizationUuid: data?.organizationUuid,
                            projectUuid
                        })}
                    >
                    ```
