### ISSUE TITLE
chore: replace moment with dayjs

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#6129]
### Description

We're depending on moment for time calculation and manipulation, but moment is no longer maintained. We should consider switching to dayjs, which has a similar api but is more modern, faster, safer (due to active maintenance) and works better with React (because it uses immutable objects). Dayjs docs here: https://day.js.org/

If we are planning on doing a fair amount of timezone-related work in the near future, we should consider doing this first. 

### What problem does this solve?

Relying on an unmaintained library is a bit dangerous. Moment is also a common source of time-related bugs because it uses mutable objects that don't play nice with React. This will also make it easier to do some of the proposed timezone work correctly.

**Comment by owlas** [comment]
I was going to close this issue since we haven't had any problems with moment. dayjs is supposed to be faster but we can't attribute any performance problems to moment currently.

However it's a good point that for security we might want to move to the maintained version. Are there known vulnerabilities in moment @magnew ?

**Comment by owlas** [comment]
Closing to track with existing vulnerability scanners
