### ISSUE TITLE
Test & compile error with wrong dbt version

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#6179]
### Description

At the moment Lightdash tries to compile the projects with dbt 1.4 and if there is an error it tries with dbt 1.5.
But the UI only shows the error for the fallback ( dbt 1.5 )

### To Reproduce

Requisites: 
- you need a dbt project for dbt 1.4.*

Steps:
- change you yml to cause a compile error
- go to project settings page
- click Test & Compile
- see error about dbt 1.5 dependencies

We should show the compile error for dbt 1.4

### App Version

0.654.0

**Comment by rephus** [comment]
I think this can happen because we install dependencies and then compile in different methods, potentially using different versions. 

For example: 

- have  a schema that works with 1.5
- have a dependency that works with 1.4

- We install dependencies using 1.4 (that works) 
- then we compile with 1.4 : it fails 
- then we compile with 1.5 . That should work, but because dependencies is using 1.4 version, that might fail.  


We should run `dependencies` and `compile` as a block, and use the same version for both.

**Comment by ZeRego** [comment]
Updated ticket title/description after debugging the problem. The issue was not directly related to the project packages versions.
