### ISSUE TITLE
Sort results data table immediately when clicking a column to sort by

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#62]

**Comment by owlas** [comment]
Nice one @hamzahc1! 

I guess you mean because when you change the sort of a column you have to rerun the query manually rather than see the results instantly change.

This is definitely a UX bug. Ideally we would pre-emptively fetch results on any change to the query in the frontend (like changing filters, metrics, dimensions, sorts, limits). 

The problem is that we might end up running a lot of large queries and overrunning analytics DBs or costing Bigquery users the mega bucks $$$$. 

E.g. Let's say you want hourly page views for the last week.
1. You select Page views
2. You select hour
3. Lightdash runs query for the entire history of data before you have the chance to filter to the last week. $$$$$$ !!

---

But then there are cases we should easily be able to do changes in memory (like sorting and filtering small sets of results). 

What do you think? 

I think my best thinking now is:
A) Make a UI improvement to show when the current query (selected filters, dimensions, metrics, sorts, limits) are out of sync with the current set of visible results. Along with a timestamp so you can also see how outdated the results are?
B) For small result sets in memory -> instantly sort in memory while we simultaneously refetch the results from the DB (i.e. data might have changed since the last run).

**Comment by TuringLovesDeathMetal** [comment]
This depends on #353
