### ISSUE TITLE
I'm able to "move" a chart from a dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6228]
### Description

I'm able to move a chart from within the chart's three-dot menu (in view mode + in the dashboard).

### Acceptance criteira

- [ ] I'm able to move charts that were created in a dashboard into a space. 
- [ ] I'm only able to move them to the space teh dashboard was in (there's no other option to move them to anywhere else in the project). 

### Analytics events

- There is an event which is triggered when a user does `move` in the three-dot-menu/header menu
- The event is called `lightdash_server_dashboard_chart_moved`
- the parameters are:
  - dashboard_id - ID of the dashboard that the chart is being moved from
  - space_id - the ID of the space that the chart is being moved to
  - context - `in_dashboard` (this is the value if you move the chart from within the dashboard delete modal. The other option is `chart_view_mode` - this is when a user clicks `delete chart` from within a dashboard)
  - user_id - ID of the user moving the chart
  - organization_id
  - project_id
  - timestamp

**Comment by PriPatel** [comment]
Hmm I think  (as a user), I would prefer it if I just had the `Move` option here in my context menu. Then in the modal, I can be told that the chart will be deleted and so I would have to close the modal and do the moving if I wanted to. Otherwise the flow is a bit weird. Also maybe I just want to move the chart anyway, it feels weird that the only way I could access that option is by deleting the dashboard first! 
<img width="274" alt="Screenshot 2023-07-10 at 20 03 34" src="https://github.com/lightdash/lightdash/assets/12776522/8d6d0bcd-27be-477c-a3f1-a6c0f8a09149">
