### ISSUE TITLE
When you expand the table calculation editor to full-screen you can't see the SQL anymore 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#6252]
### Description

If you click the expand button in a table calculation - all the SQL disappears and you can't go back to the smaller screen. You have to exit the editor and open it again. 

### To Reproduce

Uploading CleanShot 2023-07-11 at 14.43.22.mp4…

**Comment by rephus** [comment]
@hamzahc1 I think the issue is that the `collapse` button is out of the screen (you can still reach it if you scroll down) , could you confirm ( I can't see your video) ? 

[Screencast from 11-07-23 17:11:49.webm](https://github.com/lightdash/lightdash/assets/1983672/fbb4353d-cb5e-4f8e-a6f0-a93b17ad7169)

This is happening because we've recently changed how modals behave (they are not centered, but there is a fixed margin top) , we should make an exception here on fullscreen mode.
