### ISSUE TITLE
Inline filter value + operator in dashboard filters UI

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6490]
### Description

maybe wait until we mantine the filter inputs first

can we mantine the form elements and not the date picker etc.? 

<img width="529" alt="CleanShot 2023-07-25 at 15 30 43@2x" src="https://github.com/lightdash/lightdash/assets/11660098/c6484752-4266-4957-9081-c61d1894ad07">

**Comment by iampranavdhar** [comment]
Can you assign this to me ? @owlas @ZeRego

**Comment by iampranavdhar** [comment]
in that we mantine the form elements and leave the date picker as it is but it looks a bit displaced, like mantine elements will have one default height and that some times doesn't match with height of date picker.

**Comment by IrakliJani** [comment]
hi @iampranavdhar thank you for your interest in contributing to Lightdash 🙌 
This is a milestone ticket and there are a lot of unknowns. Me and @joaoviana are actively working on it. If you are interested in mantine tickets I suggest having a look to this list https://github.com/lightdash/lightdash/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%94%B7+Blueprint%22+no%3Amilestone+sort%3Acreated-asc+label%3A%22%F0%9F%99%8B+good+first+issue%22

**Comment by iampranavdhar** [comment]
And one more think. I have worked on this for sometime and here is what it looks like.

<img width="693" alt="image" src="https://github.com/lightdash/lightdash/assets/73348574/5f9cbd23-ebae-4036-96d2-5d3225a3079d">

Not completed, but just small work around. Just wanted to let you know how it is looking. And one more thing to note is I was not able to find any component in mantine with such leftside dropdown and right side text input by default. So you might have to use dropdown sperately and text input seperately. And if you want to use the same component for both new filter addition and older filter editing then there are some fields where there are three columns, and it looks bit odd and effects user experience. 

<img width="733" alt="image" src="https://github.com/lightdash/lightdash/assets/73348574/100b237c-e11c-4602-a200-1f49404c828b">

Posting this so that you can take that up, on considering this. 

Thanks!
