### ISSUE TITLE
Embedded Analytics

### ISSUE THREAD

**Issue by wahmedswl** [lightdash/lightdash#6633]
### Description

Is there any support for embedded analytics so that in can be embedded in existing portal etc?

### What problem does this solve?

Sometimes its needed to embedded the reports in existing product etc

**Comment by owlas** [comment]
Hey @wahmedswl - could you explain some more about how you'd want to embed this? What is the existing portal you'd like to embed Lightdash within?

**Comment by wahmedswl** [comment]
@owlas Something like Native controls for Web and API that will be used by the controls. Iframe solution really don't work, Power BI gives iframe based solution.

**Comment by etadelta222** [comment]
+ 1 @owlas . Found this while searching for existing feature requests. We would like to embed iframe into an internal portal so that end users can use `Query on tables` option to pick and choose columns/filters to generate a chart and export. 
Found this and looking into it as well: https://github.com/lightdash/lightdash/issues/1033 and I see this is close to end: https://github.com/lightdash/lightdash/issues/3897

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as completed - Lightdash now supports embedding. There's more details in the docs here: https://docs.lightdash.com/references/embedding

**Comment by dis-sid** [comment]
Is it available here ? According to the documentation linked by @TuringLovesDeathMetal it's a paid feature. Since it's an open source repository I wouldn't count it as "completed" if the solution source code is private.
