### ISSUE TITLE
There is a lag between hovering over a chart's information icon and seeing the accurate number of dashboards it belongs in

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#6735]
https://www.loom.com/share/4899dc8737e24ea5abb803efa40d3137

When I hover over the information icon, I can see it says `Used in 0 dashboards` briefly before it updates to show the accurate number. This could be misleading if I'm scanning through this quickly and I might delete a chart that I believe isn't being used anywhere

**Comment by ujwalkumar1995** [comment]
Hey @PriPatel 
I have analysed the issue. The data in the information icon is being fetched from an api call, that is why it is showing up as 0 until the response is received. The issue is more prominent on a very slow network. I had to throttle the api in my local setup to replicate it. 
One quick fix could be to add a loader till the api returns. Have attached video for reference. Please let me know if this works, would be happy to submit a PR.

https://github.com/lightdash/lightdash/assets/20976813/a8a7c0cc-fee6-4ac4-93a0-d931cc4f3fec

**Comment by PriPatel** [comment]
Thanks @ujwalkumar1995
