### ISSUE TITLE
I would like to be able to bulk-manage users member in my project

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#6785]
### Description

Users reported that when creating a separate project (for experimentation) they can't remove other members from that current project. This Project would just be for a single-member use, but then others get added to it and their roles get inherited from the organisation's member-role settings.

It's not currently possible to edit the members in the project, as they belong to the organisation and then cascade into the _child_ projects

### What problem does this solve?

Easier management of members in a project

**Comment by TuringLovesDeathMetal** [comment]
hmmm - I think this issue is a blend of a couple of issues. 

1. organization-level roles are confusing (it's unintuitive to a lot of people that there even are organization-level roles). Instead, we should just have project-level roles, and then organization-level admins. 
2. I want to be able to add multiple people to a project/org at once: https://github.com/lightdash/lightdash/issues/3025

I'm going to close this issue, because I feel like the title doesn't quite match the description (and there are other, more specific open issues like the ones listed above which solve this).
