### ISSUE TITLE
Show SQL join logic in lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#68]
When tables are joined together in lightdash, you should be able to see the SQL logic used to join these tables.

https://sketch.cloud/s/d6f235ac-00e3-4414-88cc-c70f88b75224

**Comment by owlas** [comment]
@TuringLovesDeathMetal are the sketch designs publicly accessible? If not I think it's enough to screenshot in the issue just for people to see

**Comment by ZeRego** [comment]
@TuringLovesDeathMetal 
I set the dialog title to be 'Join details' instead of 'Join on' to be consistent with the tooltip text. Do you wan't me to change it ? currently the sql contains artefacts like `${}` should I remove those ? 
Preview: 
![Screenshot 2021-06-24 at 10 28 46](https://user-images.githubusercontent.com/9117144/123239194-09a81680-d4d7-11eb-9ce2-322206a4cb7c.png)

**Comment by owlas** [comment]
@ZeRego those variables get resolved on the backend. I could make a new endpoint to "compile" just the join string? 

In fact, if you look in the "sql" box at the bottom of the page, you'll see the complied sql string with templates resolved

**Comment by ZeRego** [comment]
![Screenshot 2021-06-24 at 11 32 20](https://user-images.githubusercontent.com/9117144/123248570-f9486980-d4df-11eb-83b8-656927d5e257.png)

**Comment by owlas** [comment]
Sick!

**Comment by TuringLovesDeathMetal** [comment]
looks amazinnnnng! 

Also, definitely prefer `join details` to `join on`. Nice one 👌
