### ISSUE TITLE
filter in explore showing a value with "is null"

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#7466]
### Description

dashboard filter showing a value with "is null"

![image](https://github.com/lightdash/lightdash/assets/962095/252ae745-9e4c-431c-852b-61710e9981e3)

note: this can be a simple UI fix or we can find underlying problem here:
it is likely that we are not clearing values when we change an operator.

**Comment by ujwalkumar1995** [comment]
Hey @IrakliJani 
I looked into this issue. The root cause seems to be due to this https://github.com/lightdash/lightdash/blob/70300a56eb9cc3cfd9f24153506a8a7fe57a24d8/packages/frontend/src/components/common/Filters/FilterRuleForm.tsx#L111 Not sure why is [1] being passed a value to the back end when the values array is empty. If we change it to empty array, the problem is fixed but I am not sure if it would have any cascading effects. From my initial analysis, I could not find any negative impact of this change but looking forward to your inputs.
