### ISSUE TITLE
If I have no metrics in my query, I want the GROUP BY in the compiled SQL to be optional

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#7661]
### Description

If a query only has dimensions and no metrics, the user would be able to choose whether to show all results or only distinct results. This option should not be available if any metrics are selected.

### What problem does this solve?

We have certain use cases (e.g. our CX team pulling a list of details about specific orders) where all that's needed is dimensional info at individual transaction level. Introducing a GROUP BY into this query has two potential downsides:

- GROUP BY is slow. This is a particular pain point when we're running queries through our Postgres-connected project (which we use to access certain low-latency data). It can unnecessarily cause such queries to grind to a halt
- It may give unexpected results, if the user (for example) forgets to select the unique transaction identifier in their query, in which case some similar (but not actually the same) transactions will look like a single transaction in the query output. Unless you open up the compiled SQL, there's nothing telling the user that the values have been grouped.

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned. 

Fundamentally, `dimensions` in Lightdash are grouping fields. Removing this logic would be a pretty massive change to the app and I think that it would add more confusion (instead of less confusion). 

For users who are advanced enough to understand what `group by` even means, I think that they should be able to perform a query in the SQL runner with their specific queries with ungrouped data!
