### ISSUE TITLE
Autocomplete in SQL runner cuts off big table names

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#780]
![Screenshot 2021-11-09 at 15 17 22](https://user-images.githubusercontent.com/9117144/140951546-28ea4133-49d4-426b-a339-17b141cf56fd.png)

**Comment by hamzahc1** [comment]
This is still pretty annoying... :(

**Comment by hamzahc1** [comment]
Still annoying 😠

**Comment by elton-okawa** [comment]
I investigated a bit and noticed that the `ace` library set `width` on more than one class and sometimes directly on DOM `style`.
The first approach would be patching `ace` classes style in order to have a more dynamic width like suggested in https://github.com/ajaxorg/ace/issues/4584,  I didn't like this because any change on the library style would break this solution and we would need some styles like `width: auto !important` to override them.

How about changing the way we suggest autocompletion? Instead of showing the entire path, we just show the table name:
✔️ Pros - Less likely to cut off table name, but might cut `database.schema` info
❌ Cons - Autocomplete will only work with table name (typing `postgres` will not have any suggestions)

![image](https://github.com/lightdash/lightdash/assets/24387035/07fd46fb-74fc-4b78-8e30-539b266725f9)

Or splitting suggestions to `Database`, `Schema` and `Table`:
✔️ Pros - Nothing will be cut off
❌ Cons - SQL references would need to be built step by step: autocomplete `database`, type `.`, autocomplete `schema`, type `.`, autocomplete `table`

![query-step-by-step](https://github.com/lightdash/lightdash/assets/24387035/4eb29ca1-5811-41d3-98d6-65bc6aeeefb6)

**Comment by yu-iskw** [comment]
Let me share a similar issue to show completions of reserved words like functions.

https://github.com/lightdash/lightdash/issues/6663

**Comment by TuringLovesDeathMetal** [comment]
closing this as not planned. We've updated the SQL runner so that this now works
