### ISSUE TITLE
I want to be able to set default values to empty in my dashboard

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7920]
### Description

When I'm in view mode in a dashboard with a filter and there's a default value set, there's no way of removing that default value from the filter and setting it to empty. 

I wish there was a way to set the filter to be `any value` when I'm in view mode. 

https://www.loom.com/share/864348297bdb4fe98bc72817ed2efccd

**Comment by PriPatel** [comment]
@TuringLovesDeathMetal I think that this ticket : https://github.com/lightdash/lightdash/issues/6760 covers the same! 

Also worth noting that half the solution there basically covers the improvements we spoke about before : ' Instead of turning a toggle on, I can just leave the field empty to represent 'any value'. 
https://www.notion.so/lightdash/Default-value-dashboard-filter-improvements-cbcd23d529fe4320a2faa67217c0d0f8

**Comment by TuringLovesDeathMetal** [comment]
Closing this as a duplicate of #6760
