### ISSUE TITLE
Support StarRocks as a integration

### ISSUE THREAD

**Issue by alberttwong** [lightdash/lightdash#7940]
### Description

StarRocks, a Linux Foundation project, is a next-generation sub-second MPP OLAP database for full analytics scenarios, including multi-dimensional analytics, real-time analytics, and ad-hoc queries. StarRocks received InfoWorld’s 2023 BOSSIE Award for best open source software.

### What problem does this solve?

Support StarRocks as another integration.  StarRocks emulates the mysql wire protocol for querying.

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. 

We only support dbt trusted adapters to connect to Lightdash: https://docs.getdbt.com/docs/trusted-adapters

This is because they have to uphold timelines to support new dbt versions. We've been blocked by non-trusted adapters in the past in upgrading the rest of our integrations, so we decided to only support these trusted adapters!

Once StarRocks is accepted as a trusted adapter, we'll definitely look at supporting it!
