### ISSUE TITLE
Can't change date granularity after exploring from a chart with date zoom

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#8257]
### Description

Explore page shows results with the date granularity, that was applied in dashboard, but results column and selected field doesn't match. 
And there is no way to change the granularity. 

Expected:
- The table header should take in account the date granularity
- Have a dropdown to update the date granularity

Or don't apply the date granularity when exploring from a dashboard chart.

### To Reproduce

https://github.com/lightdash/lightdash/assets/9117144/fa8af84f-058e-41ee-af2c-01e638e0a1c5

### App Version

0.898.4

**Comment by joaoviana** [comment]
"Date granularity unavailable. `Explore from here` won't apply date zoom"

**Comment by joaoviana** [comment]
Decided to disable this feature: Date Zoom + Explore From Here because of some technicalities to consider: 
* We would have to do a find+replace all. So, a recap:
```
metricQuery.dimensions , metricQuery.sorts -> replace dimension name
metricQuery.metadata -> simply remove
chartConfig.config.
eChartsConfig.series(?)
tableConfig.columnOrder -> replace dimension name
```
* This could lead to strange behaviour because we've got many parts to update: `metricQuery`, `fields`, `tableConfig`, `echartsConfig`, `chartConfig`. 
* Every future feature would have to have this date zoom into consideration
* What if the explore does not have the date dimension that was overridden (e.g. it has `date week` but no `date quarter`)? We were considering turning it off for this case anyway, but potential feature: Explorer + Date Zoom 

Suggestions from feedback
* When the new date dimension doesn't exist on the explore, should we create a Custom Dimension that will fulfil that?
* `support date zoom in the explore and granularity be part of the metricQuery`
