### ISSUE TITLE
Remove ace editor

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#8299]
### Description

Once we are using monaco for all of the code inputs in Ligthdash, we should make sure to remove the ace editor.

**Comment by TuringLovesDeathMetal** [comment]
I'm going to close this issue as not planned 👀 @magnew i feel like we probably have some tests/something that checks to see what packages are installed, but not used? I'm going to hope that it's caught by that 🤞 since we've already made changes to the SQL editor and will soon make changes to the table calculation editor
