### ISSUE TITLE
As an admin, I can't see when a chart is used in a dashboard when the dashboard is in a private space

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8318]
### Description

As an admin, I'm able to access all charts/dashboards. But, if I look at a chart that has been added to a dashboard that's in a private space (that I haven't been explicitly invited to...but I can't be, because I'm an admin), then I don't see the chart as being used anywhere. 

https://www.loom.com/share/0e4d4f9dd1c841108e8b1df4ba7ee902?from_recorder=1&focus_title=1

I'd expect to be able to see that the chart was added to a dashboard as an admin.

**Comment by dansreis** [comment]
Hello @TuringLovesDeathMetal 

From a quick look through the code, I see the issue can be on of the following:

1. The frontend code is missing a query param _"includePrivate"_ **when it's an Admin user**
2. The backend code should by design:
a. Always allow the **Private Spaces** 
b. Override this _"includePrivate"_ **when it's an admin user**

If you want, I can fix this in a couple of days.


<img width="1791" alt="Screenshot 2023-12-14 at 20 24 56" src="https://github.com/lightdash/lightdash/assets/9052608/00392549-3fcd-4d3f-9041-308115b01471">
