### ISSUE TITLE
'Generating preview' toast persists after the action is complete and when I've closed the modal 

### ISSUE THREAD

**Issue by PriPatel** [lightdash/lightdash#8680]
<img width="1214" alt="Screenshot 2024-01-22 at 12 34 04" src="https://github.com/lightdash/lightdash/assets/12776522/94535fb4-e34d-48ac-a8c4-87b46626e1f9">

The toast persists even though the preview has already been generated. It remains once I've closed the modal as well. I can still dismiss it, but as a user, I'm unsure as to why anything is still generating.

**Comment by jogeshwar01** [comment]
@PriPatel As the export dashboard form also uses the useToaster hook, this would have been fixed in #8659.

Here is the output -

![image](https://github.com/lightdash/lightdash/assets/85165953/01e9afa9-38d9-4974-b5ae-47bbada52c19)

When preview generation is successful -

![image](https://github.com/lightdash/lightdash/assets/85165953/5fd47d25-da4b-4246-9db3-335c2dfb3c93)
