### ISSUE TITLE
Add "!true" and "!false" metric filter types

### ISSUE THREAD

**Issue by GtheSheep** [lightdash/lightdash#8728]
### Description

I want to be able to filter my boolean values like `!false` and `!true` in metric filters.

If you tyr to do this today, then you get an error:

"No function implemented to render sql for filter type notEquals  on dimension of boolean type"

This has been problematic when using JOINs to table that do not have the same level of completeness as the base table and trying to apply filters

### Acceptance criteria

- [ ] `!true` and `!false` work as metric filters using boolean dimensions
- [ ] we've updated the filters docs: https://docs.lightdash.com/references/metrics#available-filter-types

**Comment by TuringLovesDeathMetal** [comment]
👋 Hey @GtheSheep 

I've made this into a feature request instead of a bug - I think that we just don't support that metric type filter for now! 

You can see all of the metric filter types we support here: https://docs.lightdash.com/references/metrics#available-filter-types

(It looks like `true`/`false` are not treated like strings - so we'll need to add a specific metric filter type for it, like we have for `null` values)

**Comment by GtheSheep** [comment]
@TuringLovesDeathMetal - opened a PR for it if anyone could comment on whether or not it makes sense as a way to go?
