### ISSUE TITLE
Localhost Database inaccessible

### ISSUE THREAD

**Issue by amin-nejad** [lightdash/lightdash#91]
My DBT project accesses the database from localhost. The database itself is remote but the connection is tunnelled to localhost:5433 as it can only be accessed using a VPN from a particular host. Anyway, all this to say that if your `~/.dbt/profiles.yml` `host` key has `localhost` as a value, then you get an error like the below after it tries and fails to access the database for some time:

```
DbtError: Error returned from dbt while executing method 'poll': Database Error
  could not connect to server: Connection refused
  	Is the server running on host "localhost" (127.0.0.1) and accepting
  	TCP/IP connections on port 5433?
  could not connect to server: Cannot assign requested address
  	Is the server running on host "localhost" (::1) and accepting
  	TCP/IP connections on port 5433?
```

I use a mac and I can bypass this by changing `localhost` to `host.docker.internal` if running Docker 18.03 or later but it would be nice if there was a better solution that didn't require me changing this. Also not sure what non-mac users need to do in order to access localhost from within the container. This should be mentioned in your docs as it seems you are assuming everyone's database is remote. My particular case is probably niche but many may be using a local database for dev purposes

**Comment by owlas** [comment]
Hey @amin-nejad thanks for raising this one!

I think you're totally right: ideally the `profiles.yml` doesn't need any adjusting at all. [We started a discussion on discourse around this](https://community.lightdash.com/t/lightdash-with-a-local-postgres-database/20)

I think your solution of using `host.docker.internal` is a good one and should work for both Mac and Windows using the Docker desktop installation.

Some alternative work arounds (off the top of my head): 
 * Use your local IP address instead of `localhost` I believe this will work inside and outside your container (run `ipconfig getifaddr en1` or `ipconfig getifaddr en0` in your terminal to get those)
 * Use environment variables and the `env_var` function to parameterise the profiles file at run time

Still this is definitely a usability bug and a big stumbling block for people that have less experience with docker+networking.

---
Also noticed it's your first bug report. @all-contributors add @amin-nejad for bugs

**Comment by amin-nejad** [comment]
Thanks for the speedy response @owlas!

**Comment by owlas** [comment]
No prob! 

I'm going to add something to the docs for using `host.docker.internal` - I think that's the best we have currently! Watch this space though

**Comment by owlas** [comment]
@TuringLovesDeathMetal I've added a docs update to help users workaround this but the underlying issue isn't solved. 

you still have to modify your `profiles.yml` to get this to work, which isn't ideal.
I'm leaving "open" but removing from the dev board until we revisit it.

**Comment by owlas** [comment]
@amin-nejad we now let you update the profiles.yml in the Lightdash UI, so you can override the host name more easily without actually needing multiple yaml files. 

I'll close this for now, feel free to open up again if it's still difficult to connect to a local postgres instance
