### ISSUE TITLE
Filters general: String filters should have autocomplete

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#920]
### Context
Users aren’t always familiar with options in a field E.g. filtering on “status” should give options “shipped, pending, …“. 

### Goal
Filters should have autocomplete for string values.

**Comment by owlas** [comment]
I can think of two ways to get these values:
1. From dbt metadata - if the column has an `accepted_values` test: [docs](https://docs.getdbt.com/reference/resource-properties/tests#accepted_values)
2. We have to profile the columns i.e. run `SELECT distinct column_name FROM table` - if we run this for every column it could get very computationally expensive. Anyone have a good idea? My best idea would be: when user firsts creates a filter for a field, we fire off a request to profile that column, and we store the results

**Comment by ZeRego** [comment]
@owlas 
I don't imagine people typing everything in the metadata. And there will always be inputs where they don't know the possible values. E.g Org names
I think option 2 is viable if we add a limit to that query as a save guard. E.g `SELECT distinct column_name FROM table LIMIT 50`.  If there are more than 50 distinct results it's most likely that that dimension is a free text field rather than an enum. 
About storing those column profiles, do you mean in memory or in the DB ? If in the DB, that will bring more complexity and work time. Would you be up for trying in memory for now ?

**Comment by ZeRego** [comment]
Third option - Show suggested values already in the results. This only requires FE work and doesn't require caching or request to the warehouse.

**Comment by owlas** [comment]
@ZeRego let's start with that and work from there!

**Comment by ZeRego** [comment]
I assume we want this in both explore and dashboard pages. Dashboards page might require a bit more work and merging possible values from the different charts but it is possible.

**Comment by PriPatel** [comment]
![Screenshot 2022-02-17 at 17 58 45](https://user-images.githubusercontent.com/12776522/154542472-9682e168-767e-440c-812c-193a0a854295.png)


@ZeRego  I imagine this would work exactly like the dimensions/metrics dropdown. Will the user be able to type to search as well, or is it just going to be a dropdown with the possible values displayed? If its just a dropdown, I would need to decide what the default state would be.

**Comment by ZeRego** [comment]
@PriPatel they will be able to search, select multiple values, and set custom values ( since we don't guaranty we have all the possible values in the suggestions )
