### ISSUE TITLE
Have a "big number" visualisation type 

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#940]
Having a big number visualisation type would be useful for displaying certain types of information on dashboards (weekly active users or any other single values).

Example below from a chart online: 
<img width="410" alt="Screenshot 2021-12-01 at 15 27 56" src="https://user-images.githubusercontent.com/14341285/144474817-5f6a46be-903c-4e80-96ac-85d38b930d0e.png">

**Comment by hamzahc1** [comment]
@TuringLovesDeathMetal Is this relatively easy for us to implement? At least a couple of times in the last few days I've wanted to add this to a dashboard 🤔

**Comment by TuringLovesDeathMetal** [comment]
I'm not sure!

If this is in the echarts library already then should be pretty easy? 🤔 

I think the chart config will be the same as we currently have (i.e. you can toggle to choose which metric/table calculation you want to have for the big number viz type). and the number will just be the value in the first row of your results table. 

@owlas @ZeRego any ideas how complex this would be?

**Comment by ZeRego** [comment]
> If this is in the echarts library already then should be pretty easy? 🤔

Echarts doesn't seem to have a 'big number' type. We would have to [build a custom type](https://echarts.apache.org/en/tutorial.html#Custom%20Series).
[All echart types](https://echarts.apache.org/en/option.html#series-line) for reference.

> I think the chart config will be the same as we currently have (i.e. you can toggle to choose which metric/table calculation you want to have for the big number viz type). and the number will just be the value in the first row of your results table.

Not sure if we need to have specific configuration for this type.

Questions:
- how does a user sets a dimension value as a big number ? 
- what happens if the user selects multiple metrics ? 
- how does a user set the second number ?

**Comment by TuringLovesDeathMetal** [comment]
> how does a user sets a dimension value as a big number ?
You can't do this. You can only set a metric as a big number

> what happens if the user selects multiple metrics ?
You can't do this. You can only select one metric. If you try to toggle on multiple metrics, we won't let you (similar to how we won't let you remove _**all**_ metrics in the chart config)

> how does a user set the second number ?
We can ignore the second number for now. We would need the chart config to change with this visualization type (e.g. instead of having the x-axis + group option, we would have an option to pick the metric for the second number)

Eventually, we would be able to automatically generate this number for you. So, we would give you options of % change or value change compared to the row before it.

**Comment by owlas** [comment]
From a lightdash user:

> The only thing I would add is to be able to add a custom prefix and suffix to the number, which might not be the same as what you want to call the chart eg '319 people' on the 'Number of People Served' chart

**Comment by owlas** [comment]
I'm a big fan of the `Statistic` component in the Ant design framework: https://ant.design/components/statistic/

I think it's a good format for a 'big number'. I think if we can do it with eCharts it'll be more visually consistent but I don't know how difficult to use that api is. Some of the eCharts api is quite poorly documented.

What do you think @nathaliabj @ZeRego ?

**Comment by ZeRego** [comment]
They have a [tutorial on how to build a custom chart ](https://echarts.apache.org/en/tutorial.html#Custom%20Series)
Docs on the [graphics api](https://echarts.apache.org/en/api.html#echarts.graphic)
Since we don't need that many graphics I don't think it will be super hard. But from my quick read I don't know how we can pass the custom settings to echarts to mimic the statistic api from Ant design.

**Comment by owlas** [comment]
Great find @ZeRego ! I don't think we need to copy the API only the visualisation. Although being able to specify the suffix is useful and unsure we can do that reliably with echarts.

It might be ok to break away from eCharts we already will have to do that for table visualisation types #430

**Comment by nathaliabj** [comment]
I think @owlas is right, i feel we could use the Ant design statistics directly from the table data and just have a check to render this one instead of our simpleCharts component (with eCharts), like we have done it in #430. I will look more into their docs and see how it works! 👀

**Comment by owlas** [comment]
Yep makes sense @nathaliabj - we don't necessarily need to use the Ant component (especially if we have to install all their dependencies!!!). 

But I like the look of it
