### ISSUE TITLE
Lightdash should not convert timezones already in UTC

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#9606]
### Description

We have a customer reporting that "all timestamps in Lightdash are being converted from EST to UTC in SQL, and then converted back to the local timezone (EST) in the browser display. The problem is that our timestamps are already stored in UTC in Snowflake."

This needs some investigation to see where we could be doing this conditionally and whether this is a Snowflake specific issue. 

If we can detect that we shouldn't convert a timezone that is already in UTC, we should not be converting it. If we can't detect it, we need to provide users with some control.

**Comment by rephus** [comment]
The snowflake conversion happens here: https://github.com/lightdash/lightdash/blob/main/packages/common/src/compiler/translator.ts#L56

Some extra details about this: 

- just a time
- has no timezone/offset stored at all
- similar to `DATETIME` in bigquery and `TIMESTAMP WITHOUT TIME ZONE` in postgres
- if created from a timestamp with an offset will just drop the offset and keep the raw time (so not UTC)

One solution could be to finally add the `organization` timezone settings, and pass this information to the method `https://github.com/lightdash/lightdash/blob/main/packages/common/src/compiler/translator.ts#L105` so we convert it to the right timezone, rather than using UTC.
