### ISSUE TITLE
Design improvements to timezone information. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9754]
### Description

We've added a button which shows you the timezone information for the queries you're running in Lightdash. This button also lets you change the timezone that is being used. 

![image](https://github.com/lightdash/lightdash/assets/31848148/986ed708-fb66-46c5-9754-7040dffd5e81)

Specifically, the timezone affects the values shown in the _**filters**_ and _**results**_ in your queries. 

We've also added timezone information when you're selecting a filter with time information.

<img width="1352" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/9d80ec50-d749-4da0-8afd-522603161757">

The reason why this is useful is because most databases store dates/times in UTC. But, most people don't "think" in UTC. 

For example, if I'm in California and it's 2PM, and I want to filter data from the last 2 hours, I'd expect to be filtering from 12PM --> 2PM PST (not from 7PM --> 9PM UTC).

We then need to store this information so that if someone in a different timezone looks at the _**same**_ chart, they'll see the same information/results. 

So, in the California example above, if I share this chart with Priyanka, who is in London, she'll see the chart filtered from 12PM --> 2PM, but there should be some indication that this is in PST. The filters and results shouldn't "switch" to Priyanka's timezone (otherwise, the chart/results would look different). 

One last bit of information that could be useful...you _**interact**_ with times/dates with times in a timezone, but when we query your warehouse, we convert _**everything**_ back to UTC. So, the dates/times you see in the filters and results could be different to the dates/times you see in the SQL block that we compile. 

Here are some examples of how this looks in other BI tools

- holistics: 
<img width="797" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/26226b8e-b3e4-4de3-92b6-47c959455d1d">

- Looker: 
![image](https://github.com/lightdash/lightdash/assets/31848148/493cc3ae-e140-4352-bd79-d5c680dc85e6)

- Amplitude:
![image](https://github.com/lightdash/lightdash/assets/31848148/81af6f12-6792-46c5-aa9a-70f18af7581e)

### What's the problem? 

We basically dumped a lot of timezone information into the app all at once. It's occupying really valuable real estate (in the filters and beside the run query button) so I want to make sure that it 100% needs to be there. Or if there's another place we can put it that's still obvious, but less like "I interact with this 80% of the time I run my queries" (since I'm expecting people to interact with this <5% of the time they run their queries). 

It also just feels a bit like "dumped information". We went with the approach of "show everything" and then we can remove things after. 

The "ugly" bit here isn't the components, more that there's a _**lot**_ of information in really valuable places that people are probably only using like 10% of the time. 

###  Expected output:

- sketches showing how timezones would change on the Explore view page (mainly this view)
<img width="1" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/b91a1cc8-3b3c-4c5b-9439-db8b943b6dca">

### Things that need to be made obvious to the user (which aren't obvious today)

1. **What their local timezone is from the list of timezones.** When you press the button that lists all the timezones, we've picked 24 timezones (to cross the 24 hours). So, the timezone you might be used to seeing could be not listed. E.g. If I live in Ottawa, my timezone will be listed as `New York` (not `Ottawa`). There should be some indication in the list of which timezone is your local timezone. 
2. **The button is affecting the timezone used in your query** Right now, the copy just says the timezone name (e.g. `Pacific/Pago_Pago`) but there's no indication that this is a timezone and that this timezone is affecting your results + filters.
3. **What timezone they're running their queries in/viewing their results in** We thought that this was most obvious if we put it beside the `run query` button. But maybe there's a better place to put this? E.g. should it be in the `results` tab? And should this be a different place if you're in the Explore view vs. in the saved chart view? 
4. **The filters and results are affected by the timezone you've selected** Right now, we've made it almost _**too**_ obvious in the filters that you're using a local timezone. (and it's really ugly). Instead, is just having this button/timezone picker and good docs enough to portray that information to the user? Or do we actually need to add timezone information to the filters?

### When is this done? 

- When users think this is easy to understand. Right now, it's easy to understand because there's _**so much stuff**_ talking about it. I want to see if we can remove some of this information and still have users from companies who are across multiple timezones understand this feature/be able to find it

**Comment by PriPatel** [comment]
**1. What their local timezone is:**
-  Add the word LOCAL in front of the time zone , maybe with that item having a different bg color?
-  Add a green blinking dot (or something similar) in front of their local time and on hover show that it's their local timezone?
   
   
   **2. The button is affecting the timezone used in your query**
   Why does it have to say the territory, and not UTC+ (X)? < that makes it more obvious that its a timezone and it also makes it more standard across the app? Then maybe on hover it says the territory name?

**3. What timezone they're running their queries in/viewing their results in** 
Im not sure if the best place is next to the Run Query button. At a glance it makes sense because its affecting everything below it.  I think maybe its best to wait for some user feedback on this one, or once its released, ask a bunch of people where they feel it should be more relevant. I don’t have enough to speculate. **The appearance of the button itself can be minimal though.** It doesn't need to look like a dropdown. 

**4. The filters and results are affected by the timezone you've selected** 
I don't think there is much we can do about the appearance without affecting what's actually being shown. I actually find it confusing . why is it showing me the UTC time, but then reminding that im looking at paris time, if its already clear that im looking at paris time from the button at the top? 
Why not just have UTC + (X) next to the field? (and delete under under the field). Then on hover, it can tell me what the utc time is. Again, probably worth doing less here to begin then, then addding more based on user feedback. 

@TuringLovesDeathMetal
