### ISSUE TITLE
Support google single sign on

### ISSUE THREAD

**Issue by avaitla** [lightdash/lightdash#983]
### **Description: What is it?**

Login should be possible using google workspace login (different and simpler than SSO). Only allow users with a @domain.com email to login.

### **Problem: What problem does this solve?**

Improved user management / compliance for companies using Google SSO as their login provider.

Also makes UX much faster when signing up

### **(Optional) Why: How do we know this is a real problem and worth solving?**

*Why are we solving this?*
*If you're a Lightdash user suggesting a feature, you can skip this!* 
*Otherwise, add any links to customer conversations or research.*

Similar to metabase google login.

### **Success: How will we know if we’ve solved this problem?**

On signup and login you can use an existing google account to access Lightdash

### **Audience: Who are we building this for?**

All users with a google workspace account for a corporate domain (similar to metabase google login)

**Comment by owlas** [comment]
Thanks for this @avaitla, we absolutely should support SSO. This is the simplest to add before #49 

@ZeRego I believe we should be able to support this using google passport plugin: http://www.passportjs.org/packages/passport-google-oauth/

**Comment by owlas** [comment]
@all-contributors add @avaitla for ideas

**Comment by owlas** [comment]
# Implementation

### Lightdash admin requirements

To enable Single Sign-on with Google the user will need to:

1. [Create a Google OAuth Client ID](https://console.cloud.google.com/projectselector2/apis/credentials) is their GCP account
2. Pass two new environment variables to the app: `SOCIAL_AUTH_GOOGLE_OAUTH2_KEY` and `SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET`

### Authenticating in Lightdash

We'll use the [passport-js google oauth middleware](http://www.passportjs.org/packages/passport-google-oauth2/). Changes we need to make:

**Frontend**
- [ ] Conditionally show a "sign in with google" button if the backend has `SOCIAL_AUTH_GOOGLE_...` correctly setup
- [ ] Show a [google login component](https://www.npmjs.com/package/react-google-login)
- [ ] When user auths with google we send the resulting access token to the backend

**Backend**
See [passport-js docs](http://www.passportjs.org/packages/passport-google-oauth2)
- [ ] New route `/auth/google` that the frontend uses to send the user's access token
- [ ] New route `/auth/google/callback` that Google uses to send the full profile information
- [ ] Business logic to update / create new user depending on the google profile
- [ ] New table in database to store google credentials

**Database**
*New table is highlighted**

Existing password auth:
* User provides email and password
* Use `emails` to find the user's `user_id`. Multiple users cannot have the same emails registered.
* Use `passwords` to find the password for the `user_id`
* If passwords match, then login!!

New google auth:
* Google provides a `google_user_id` and an `email`
* We search `emails` for an existing user with a matching `email` to the google account
* If there is no matching email, create a new user with `user_id`. create an associated entry in `emails` and `google_auth_ids`. But there will be no entry in `passwords`.
* If there IS a matching email in the `emails` table, then an existing Lightdash already registered a user that the google profile uses. We should get the user to provide their password to prove it's them. Once they pass the test, we can associate `google_user_id` with the existing `user_id`

This requires just one more table in the database `google_auth_ids` that contain the `google_ids` for each user. There will be one or zero `google_ids` for each `user_id`

<img width="1050" alt="Screenshot 2022-01-06 at 13 54 08" src="https://user-images.githubusercontent.com/11660098/148393388-e870a74c-1a85-4697-a6c1-5688c1e9d49d.png">

**Comment by owlas** [comment]
Google has recently updated their sign-in experience and recommend using the [Sign in with Google button](https://developers.google.com/identity/sign-in/web/sign-in). I've tried integrating this and I have a few problems with it:
1. It uses the [oauth implicit flow](https://developers.google.com/identity/protocols/oauth2/openid-connect), which is inherently less secure than the alternative server flow.
2. It is rendered dynamically by [pulling the src from a CDN](https://developers.google.com/identity/gsi/web/guides/client-library). I feel like it would be too unreliable for a UI component we really need to render. I don't mind this approach for things like sentry/rudderstack
3. The flow isn't out-of-the-box compatible with any of the [google passportjs strategies](https://www.passportjs.org/packages/) because it makes a POST request to the backend. We'd need some small middleware.

All to say I'm going to go ahead with the standard OAuth2.0 backend using OpenID Connect because it's more secure, integrates with passportjs and so we can standardise social logins.

**Comment by owlas** [comment]
Hey @avaitla , 

We've just shipped limited support for google SSO. I'm opening a new issue to track the outstanding work
