### ISSUE TITLE
Add raw option for date time intervals

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#994]
Time intervals currently does not have a raw option for genuine use cases where you want the original timestamp.

e.g. in a table calc/custom dimension where you want to calculate time difference between fields
OR a product use case where you want to order some events by sequence and know the time they happened to a high level of precision

**Comment by djayatillake** [comment]
https://github.com/lightdash/lightdash/blob/3c85875f73cfcb1f8f599609c5454447fed8ba73/packages/frontend/src/utils/resultFormatter.tsx#L50

Does the default in this switch statement and at L18 mean we don't actually need to solve this issue? @owlas

**Comment by ZeRego** [comment]
@djayatillake 
> Does the default in this switch statement and at L18 mean we don't actually need to solve this issue? @owlas

The `formatTimestamp` is only responsible for formatting a timestamp in the UI. The timestamp comes truncated already from the database since we use `data_trunc()` for those dimensions.

 ### What are we trying to achieve ?

If I understand correctly, what we want is to have the raw timestamp value when we breakdown the timestamp dimension into time interval dimensions. 

The default intervals for timestamps are : millisecond, day, month, year and we want to replace the millisecond interval with the raw timestamp. So we would end up with: raw, day, month, year. 

### How/where we breakdown the timestamp ?

When we are converting a dimension from dbt model we check their type and if they have a `time_interval` value. If so we set the default intervals. 

https://github.com/lightdash/lightdash/blob/main/packages/backend/src/dbt/translator.ts#L248

We then create extra dimensions per each time interval. 

https://github.com/lightdash/lightdash/blob/main/packages/backend/src/dbt/translator.ts#L269

In the `convertDimension()` function we wrap the sql to have `data_trunc()`.

https://github.com/lightdash/lightdash/blob/3c85875f73cfcb1f8f599609c5454447fed8ba73/packages/backend/src/dbt/translator.ts#L68

### What we need to change ? 

- We would have to change the default value from 'milliseconds' to 'raw'

https://github.com/lightdash/lightdash/blob/3c85875f73cfcb1f8f599609c5454447fed8ba73/packages/backend/src/dbt/translator.ts#L261

- Don't change the sql when creating the dimension with interval 'raw'. That way we keep the sql from the original dimension.

https://github.com/lightdash/lightdash/blob/3c85875f73cfcb1f8f599609c5454447fed8ba73/packages/backend/src/dbt/translator.ts#L86
