### ISSUE TITLE
Area charts aren't plotting properly with multiple series

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9972]
### Description

The area charts seem to be zig-zagging between points. 

https://analytics.lightdash.cloud/share/9DW1MIG_9-fJgz5bfpSxc

<img width="758" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/4092ca79-eb29-4796-a2b7-39bc41eff825">

See a user running into the same issue here: https://lightdash.slack.com/archives/C04NZSMM9LZ/p1714741703997629?thread_ts=1714658660.022519&cid=C04NZSMM9LZ

^It looks like their chart is zig-zagging at the point where the series has no value for the x-axis value

### Steps to Reproduce the Bug or Issue

1. create a chart with multiple series (i.e. grouped)
2. create an area chart

### Cloud or self-hosting

cloud

**Comment by rephus** [comment]
This is because we are first sorting by `partner name` first, not by the x-axis, so the results in `list` will appear  in different order , 

![Screenshot from 2024-05-06 15-01-24](https://github.com/lightdash/lightdash/assets/1983672/9597beb3-8418-4738-b6ea-c24ce6ab4b54)

If we remove the partner name, then it is fixed.

![Screenshot from 2024-05-06 15-01-31](https://github.com/lightdash/lightdash/assets/1983672/e96ffc97-8045-4d68-9f86-2d87bd4e866b)

IIRC this is automatically fixed for charts with single series, but not when there are multiple series / groups; because automatically sorting by `x-axis` in that case will cause some other bugs.

**Comment by TuringLovesDeathMetal** [comment]
Closing this issue as not planned. 

Instead, I've opened a new issue related to this here: https://github.com/lightdash/lightdash/issues/9991
